- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
> Cherry-pick fix for MDA timeout at short exposures

- autofocus/OughtaFocus.java
This is a more or less verbatim backport of the code present in OughtaFocus 1.4 and not in OughtaFocus 2.0.  Jon added two methods (MedianEdges and FFTBandpass) that now can also be used in 2.0.
> Oughtafocus: forward port of additions made by Jon Daniels in September 2015

- bindist/Makefile.am
Cherry pick r15942 from 1.4 master.
> Unix build: Distribute diSPIM_Tools macros

- autofocus/OughtaFocus.java
There should be no functional consequences and this should help towards getting rid of dependency on (the very outdated) commons math2 library.
> mm2:  Upgraded OughtaFocus plugin to use math commons 3 rather than 2 library

- autofocus/OughtaFocus.java
This amends #210 to restore the original tolerance settings. See my comments to #210.
> Correct tolerance settings for OughtaFocus

- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingProcessor.java
The plugin try to add metadata to UserData even in Live mode, which result in null pointer exception because this metadata does not exist in live mode.
This PR should fix it.
> Fix shading plugin live mode

- DeviceAdapters/GenericSLM/GenericSLM.cpp
- plugins/Projector/src/main/java/org/micromanager/projector/Galvo.java
- plugins/Projector/src/main/java/org/micromanager/projector/ProjectionDevice.java
- plugins/Projector/src/main/java/org/micromanager/projector/ProjectorControlForm.form
- plugins/Projector/src/main/java/org/micromanager/projector/ProjectorControlForm.java
- plugins/Projector/src/main/java/org/micromanager/projector/ProjectorPlugin.java
- plugins/Projector/src/main/java/org/micromanager/projector/SLM.java
Fixes a bug in the Generic SLM Device Adapter that causes MM to crash hard.
Adds Checkerboard option to the Projector plugin (very helpful for alignment).
Improves documentation somewhat and speeds up calibration of SLM devices.
> Projector plugin and Generic SLM

- plugins/CRISP/src/main/java/org/micromanager/CRISP/CRISP.java
- plugins/CRISP/src/main/java/org/micromanager/CRISP/CRISPFrame.java
These are relatively minor, and several slightly hacky improvements, but at least make the plugin work more reliably.  To get things working well, the ASIStage adapter would need a major re-write.
> Crisp plugin, Made calibrate and focus curve buttons work again.

- mmstudio/src/main/java/org/micromanager/internal/positionlist/AxisData.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/AxisTableModel.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionListDlg.java
When creating the position list dialog, the stages that were selected
during the last session in the given profile will be selected again.
Code to store their usage in the profile was already present, restoration
was not.  Also added some headers, made several variables final and
added some documentation. Addresses issue #335.
> PositionListDlg: remember selected stages between application starts.

- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ImageCollection.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ImageUtils.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/MultiChannelShading.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/MultiChannelShadingFactory.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/MultiChannelShadingMigForm.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingException.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingProcessor.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingTable.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingTableModel.java
Removed most dependencies on Micro-Manager internal code.
Deleted code paths that were no longer used.  Added several file headers,
removed unused import statements, and added several comments.
There should be no functional differences.
>  MultiChannelShadingPlugin refactoring

- mmstudio/src/main/java/org/micromanager/internal/utils/MDUtils.java
Several cameras return bining in the form of 1x1 rather than just 1.
When such strings propagate to the MDUTils function, binning will
not be recorded in the metadata.  This change tests for such strings
and will translate the string into an integer when possible.
There are also a few additions to Javadoc and standardized variable
naming.  I could not test this change since I have recently been a
unable to run my own code in NetBeans.
> Likely fix for handling of binning Strings

- mmstudio/src/main/java/org/micromanager/internal/utils/MDUtils.java
(Even though they shouldn't be.)
Alternative to #341.
> Parse ROI strings correctly when values are negative

- mmstudio/src/main/java/org/micromanager/internal/script/BeanshellEngine.java
Catch another situation in which no user feedback was given upon a parsing error
> Beanshell error reporting: Fix another user feedback issue

- mmstudio/src/main/java/org/micromanager/display/HistogramData.java
- mmstudio/src/main/java/org/micromanager/display/internal/ContrastCalculator.java
- mmstudio/src/main/java/org/micromanager/display/internal/inspector/ChannelControlPanel.java
- mmstudio/src/main/java/org/micromanager/internal/graph/HistogramCanvas.java
Fix #387 and some other minor issues.
> Fix some histogram issues

- mmstudio/src/main/java/org/micromanager/internal/utils/DaytimeNighttime.java
Also added Separator and TableHeader, but did not check if those work.
> DayNightTime: Add TitledBorders to the Day/Nighttime control.

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
> Clean up program initialization

- autofocus/src/main/java/org/micromanager/autofocus/Autofocus.java
- autofocus/src/main/java/org/micromanager/autofocus/AutofocusDuo.java
- autofocus/src/main/java/org/micromanager/autofocus/AutofocusTB.java
- autofocus/src/main/java/org/micromanager/autofocus/HardwareFocusExtender.java
- autofocus/src/main/java/org/micromanager/autofocus/OughtaFocus.java
- mmstudio/src/main/java/org/micromanager/events/AutofocusPluginShouldInitializeEvent.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/pluginmanagement/DefaultPluginManager.java
This addresses #374 and fixes a sporadic failure to start Micro-Manager.
Also improves behavior of a few autofocus plugins when the hardware configuration changes.
> Fix loading of autofocus plugins

- mmstudio/src/main/java/MMStudioPlugin.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
> Startup and shutdown fixes

- mmstudio/src/main/java/org/micromanager/alerts/internal/AlertsWindow.java
Also removed unused imports and added a bit of missing Javadoc.
> mmstudio: Make Alerts Window remember its position.

- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/internal/menus/FileMenu.java
so that the progress dialog actually becomes visible.  The same strategy
as correctly used in the implementation of the OpenRecentMenu was applied
to the promptToOpenFile method.  Also removed some superfluous imports and
other minor fixes.
> mmStudio: File Open command now runs on its own thread,

- mmstudio/src/main/java/org/micromanager/internal/hcwizard/FinishPage.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/IntroPage.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/MicroscopeModel.java
Fixes Issue #430.  Also beautifies the code a bit.
> HCWizard: Previous filename is no longer proposed when creating a new configuration.

- mmstudio/src/main/java/org/micromanager/internal/utils/GUIUtils.java
> GuiUtils: Fix bug causing windows not to be shown when parent window top left corner was not on a screen.

- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayWindow.java
Addresses issue #458.  This likely needs more study, but at least makes MM usable again.
> Temporary fix for MDA hang

- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayWindow.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/ZWheelListener.java
Fixes bug #454.  This PR includes two other PRs (as it is not possible to run MM without them).
> ZWheel Listener, fix bug that caused it to not work on newly opened windows

- mmstudio/src/main/java/org/micromanager/display/internal/HyperstackControls.java
- mmstudio/src/main/java/org/micromanager/display/internal/ScrollbarAnimateIcon.java
- mmstudio/src/main/java/org/micromanager/display/internal/ScrollerPanel.java
Rather than the last remembered position.  Also some code cleanup. Addresses issue #442.
> Causes viewer playback to start at current position

- plugins/FrameCombiner/src/main/java/org/micromanager/plugins/framecombiner/FrameCombinerConfigurator.form
- plugins/FrameCombiner/src/main/java/org/micromanager/plugins/framecombiner/FrameCombinerConfigurator.java
Also improved UI somewhat.  Needs conversion to MigLayout.
> FrameCombiner plugin now remembers window position.

- plugins/MultiAndor/src/main/java/org/micromanager/multicamera/MultiCameraFrame.java
In the OnPropertyChanged handler, place the call to update the camera on
the EDT.  Also add a flag so that the GUI will only be refreshed when the
user changes the state of the camera dropdown (rather than any other event
that changes the active camera).  This remains tricky code, however, I tested
it on our "Superscope", where the old code invariably resulted in deadlock
(most of the time on the first try), whereas this changed code remains deadlock-free.
> MultiCamera plugin: Avoid deadlock.

- autofocus/src/main/java/org/micromanager/autofocus/OughtaFocus.java
Code written by Jon Daniels, see PR #484
> Oughtafocus: Adds Tenengrad algorithm.

- mmstudio/src/main/java/org/micromanager/internal/script/ScriptPanel.java
Puts the line failing on linux between a try-catch.  Also cleans up the ScriptPanel code somewhat.
> Script panel linux fix

- mmstudio/src/main/java/org/micromanager/internal/positionlist/TileCreatorDlg.java
Also handles application shutdown appropriately.  Addresses issue #481.
> TileCreator: remembers overlap setting.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
> Set default for Sync Exposure setting true

- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
Re-introduce the use of NumberUtils.  Also removes the use
of intermediate values (values are now always read from the
input text fields and written to profile only when the
window is disposed), simplifying the code. Different step
values for different Z stages are now correctly stored.
Addresses issue #506 .
> StageControl: Convert Numbers and Strings depending on locale.

- mmstudio/src/main/java/org/micromanager/internal/utils/DaytimeNighttime.java
Also fixes a typo in "ToolBar".
> DayNightTime: Fixes text color in Dialogs and ScriptPanel in Night mode.

- mmstudio/src/main/java/org/micromanager/display/internal/DefaultImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/ExportMovieDlg.java
Dialog now remembers its position.  Better naming of dialog.
Better naming of resulting ImageJ window.  Fixes failing export
of snap window (i.e. no non-zero axis).  Fixes many
warnings shown in Netbeans.
> mmstudio: Improvements and fixes for movie exporter.

- mmstudio/src/main/java/org/micromanager/alerts/internal/AlertsWindow.java
- mmstudio/src/main/java/org/micromanager/alerts/internal/CategorizedAlert.java
- mmstudio/src/main/java/org/micromanager/alerts/internal/DefaultAlert.java
- mmstudio/src/main/java/org/micromanager/alerts/internal/DefaultAlertManager.java
Avoids Alert window stealing focus.  Adds Copy All button so that content of the Alerts Window can be copied.  Adds JavaDoc in many places.
> mm2 alert improvements

- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorPluginFrame.java
- plugins/ZProjector/build.xml
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorException.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPlugin.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginExecutor.java
A gear icon plugin that generates a Z projection of the current dataset.  All axes (time, channel, position) are included in the projection, and the resulting dataset has the same dimensions as the original (except for the number of slices, which is now 1).
> Z projector plugin

- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/DataCollectionForm.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/MainForm.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/PairDisplayForm.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/data/LoadAndSave.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/data/RowData.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/datasetdisplay/ParticlePairLister.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/fitmanagement/FitAllThread.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/fitmanagement/GaussianTrackThread.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/internal/tabledisplay/DataTableModel.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/spotoperations/SpotLinker.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/utils/ListUtils.java
Improvements in calculating distances between spot pairs.  Also fixes several bugs in saving of spot data.
> Localization Microscopy plugin progress

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/OMEMetadata.java
> OME metadata: fix wrong stagelabels.

- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/PairDisplayForm.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/datasetdisplay/ParticlePairLister.java
- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/fitting/P2DFitter.java
Version as used in the submitted Localization Microscopy plugin
> Merge changes in localization Microscopy plugin

- DeviceAdapters/DemoCamera/DemoCamera.cpp
- mmstudio/src/main/java/org/micromanager/internal/utils/ImageUtils.java
This fixes the display of RGB images.
> Backport RGB display fix from mm2-next

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultImageJConverter.java
Fix the conversion of ImageJ RGB imags to Image
> Fix the conversion of ImageJ RGB imags to Image

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AffineEditorPanel.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelPresetEditor.java
and offers to calculate one if it is not, on pressing OK in pixel preset editor
> Studio-PixelConfig: Checks if affine transform is reasonable

- mmstudio/src/main/java/org/micromanager/internal/hcwizard/MicroscopeModel.java
> Studio-HCW: Fixes bug in reading affine transforms from config file.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/CalibrationListDlg.java
Pixel Size Calibration dialog now prompts to save config file if any changes were made to any of the pixel size configurations. As suggested by Nick Anthony.
> Pixel config Calibration usability improvement

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
This PR implements the ability to programatically set the zoom of a display. The methods involved are already included in the DisplayWindow interface but were left unimplemented.
> Implement setting of zoom ratio in DisplayController

- mmstudio/src/main/java/org/micromanager/internal/propertymap/NonPropertyMapJSONFormats.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPlugin.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginExecutor.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginFrame.java
Enable Zprojection to dataset on disk.  This should help with large datasets.  TODO: progress reporting.
> Projection on disk

- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginExecutor.java
This improves the UI significantly in case of missing data
> ZProjector: show alerts instead of errors.

- DeviceAdapters/FakeCamera/FakeCamera.h
- DeviceAdapters/MicroPoint/MicroPoint.cpp
- DeviceAdapters/OxxiusCombiner/Oxxius_combiner.cpp
- DeviceAdapters/WieneckeSinske/WieneckeSinske.cpp
- doc/how-to-build.md
- plugins/MMClearVolumePlugin/build.xml
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/CoordsComparator.java
Only c++ files. Java is out of this fix.
Refer also to https://github.com/micro-manager/micro-manager/pull/721 aborted
> Ubuntu18.04 fix only cpp

- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/internal/menus/FileMenu.java
- Close all menu item is now disabled if there are no displays to be closed
- If all displays can be closed without prompting, a single simple confirmation dialog is presented.
Addresses issue #424
> Refinement of Close all menu item

- DeviceAdapters/Skyra/Skyra.cpp
- DeviceAdapters/Skyra/Skyra.h
- DeviceAdapters/Skyra/Skyra.vcxproj
- DeviceAdapters/configure.ac
Bit tough without a Mac, but works.  All pulled in through the svn repo.
> Skyra adapter updates to make it compile on Mac

- mmstudio/src/test/java/org/micromanager/data/internal/VersionCompatTest.java
This fixes compile but tests still fail.
> Fix mmstudio test imports

- .gitignore
- configure.ac
- m4/mm_gmock.m4
- testing/Makefile.am
- testing/setuptesting.sh
Download URL for googletest was broken.
> Fix C++ test setup

- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/CenterAndDragListener.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYNavigator.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYZKeyListener.java
Bug in CenterAndDragListener (caused by confusing pixels with microns) was fixed. 
A warning dialog is now shown when the user requests to set the distance to move more than 2x the field of view. Even if this would avoid one destroyed objective, it is worth it.
> Navigation code improvement. Closes #776

- MMCore/MMCore.cpp
(Just because I nearly got confused myself.)
> Add to comment about MMCore versioning

- plugins/MMClearVolumePlugin/src/main/java/edu/ucsf/valelab/mmclearvolumeplugin/CVViewer.java
Fixed pixel import.  Much cleanup.
> ClearVolume viewer

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
Second attempt fixing this:
The elapsedTime and image number tages can be inserted either
by the circular buffer or the camera.  WHen different systems are
used, calculating fps becomes very difficult (after circular buffer
overflow).  This commit adds ugly heuristics to deal with all
possible permutations, but the situation should really be cleared
up in the C++ layer.
> Studio: make camera fps work again for cameras other than Demo.

- buildscripts/ivy.xml
- plugins/Assemble/src/main/java/org/micromanager/assembledata/AssembleDataAlgo.java
Now morphs overlapping areas from source images nicely.  Waited for boofcv release to merge.  Increases boofcv and friends version (hope that does not cause problems elsewhere).
> Assemble plugin: avoid ugly borders when stitching

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
Still not exactly sure how it can occur, but the new code ensures
correctness
> Studio: Avoid possible IndexOutOfBoundsException in MMAcquisition.

- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
Specifically issue #828, but possibly others as well.  Closes #828.
> Studio: Fixes display issues when switching from MultiCam to Single Cam

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/ExploreControlsPanel.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/MagellanMouseListener.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/MagellanOverlayer.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/SurfaceGridPanel.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/ExploreAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanGUIAcquisition.java
Pycro-manager: 0.7.7
NDViewer: 0.2.1
> Fix magellan bugs and bump library versions

- plugins/RTIntensities/build.xml
- plugins/RTIntensities/src/main/java/org/micromanager/plugins/rtintensities/RTIntensities.java
- plugins/RTIntensities/src/main/java/org/micromanager/plugins/rtintensities/RTIntensitiesFrame.java
PLugin written by Carlos Mendioroz.  Closes PR #790 that ran into some merge conflicts.
> Adds Real Time Intensity plotting plugin

- buildscripts/ivy.xml
Fix bugs with ZMQ server missing interfaces and multi-camera not working
> Pycro-manager: 0.7.8; AcqEngJ: 0.5.2

- mmstudio/src/main/java/org/micromanager/internal/dialogs/IntroDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ProfileSelectionUIController.java
This helps the user locate their own profile, and also ensures that the
skin is set correctly (fixing a bug where skin is incorrect when the
user skin differs from the default).
> Studio: Startup dialog now changes skin when profile changes.

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
> Studio: Avoid null pointer exception while storing MPTiff

- buildscripts/ivy.xml
Fixes data writing bug in magellan
> bump versions: pycromanager java: 0.7.12  AcqEng: 0.5.5   NDTiffStorage: 0.3.0

- autofocus/src/main/java/org/micromanager/autofocus/HardwareFocusExtender.java
This PR contains minor changes to the HardwareFocusExtender code that are unlikely to effect usage.
1. Comments are added to further explain variables, return values, etc.
2. Debug level logging is added so that performance of the extender can potentially be analyzed in retrospect.
3. An potential error is avoided that would occur if a hardware focus device other that the Nikon TI PFS were to have a property called `Status`.
> HardwareFocusExtender: Add comments, fix potential future bug, add debug logging.

- buildscripts/ivy.xml
For making AcqEngJ use snapImage and adding support for external camera triggering
> PycromanagerJava to 0.8.0; AcqEngJ to 0.6.0

- micromanager.sln
git-svn-id: https://valelab.ucsf.edu/svn/micromanager2/trunk@17331 d0ab736e-dc22-4aeb-8dc9-08def0aa14fd
> Build: Remove TriggerScope2 from solution

- micromanager.sln
git-svn-id: https://valelab.ucsf.edu/svn/micromanager2/trunk@17332 d0ab736e-dc22-4aeb-8dc9-08def0aa14fd
> Build: found empty line in solution causing automated build to fail

- buildscripts/ivy.xml
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/api/MagellanAPI.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/main/Magellan.java
+ Some insignificant magellan changes I accidentally included
> Fixed classloader for plugins bug when launching ZMQServer. Pycromanager to 0.8.6

- mmstudio/src/main/java/org/micromanager/internal/diagnostics/ReportSender.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/ConfigWizard.java
- mmstudio/src/main/java/org/micromanager/internal/utils/HttpUtils.java
> Studio: change urls to https.  Added comment to implement

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
add multi-resolution feature to NDTiffStorage
> NDTiffStorage to 0.3.1; Pycro-manager-Java to 0.8.10 

- buildscripts/ivy.xml
> NDViewer to 0.2.6; NDTiffstorage to 0.3.2; PycromanagerJava to 0.8.11

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
introduced in refactoring of sequencesettings on July 17th.
> Studio: Fixed bugs in acquisition setting handling

- mmstudio/src/main/java/org/micromanager/events/ApplicationSkinEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultApplicationSkinEvent.java
- mmstudio/src/main/java/org/micromanager/internal/utils/DaytimeNighttime.java
ApplicationSkin#setSkin stated that the event would be posted, but the
event didn't actually exist.
> Add ApplicationSkinEvent that is posted when the skin mode is changed

- buildscripts/ivy.xml
- Fix ZMQ null behavior
- Correct channel switching logic in AcqEngJ
> AcqEngJ 0.6.4 Pycromanager Java 0.8.13

- buildscripts/ivy.xml
Various new Pycromanager bug fixes and features
> AcqEngJ  to 0.6.5; Pycromanager Java to 0.8.14

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/MagellanViewer.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
Add RGB mode to NDviewer/NDTiffStorage/Magellan
> NDViewer 0.2.8; NDTiffStorage 0.3.4; Pycromanager 0.8.16.

- libraries/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/utils/P2D.java
- plugins/Emu/src/test/java/de/embl/rieslab/emu/swinglisteners/SwingUIListenersTest.java
- plugins/Emu/src/test/java/de/embl/rieslab/emu/ui/uiparameters/StringUIParameterTest.java
- plugins/Emu/src/test/java/de/embl/rieslab/emu/ui/uiparameters/UIPropertyParameterTest.java
This fixes the last 4 files listed in #945 by @zhangxiaosa.
> Remove or escape non-ascii chars in Java source

- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelPresetEditor.java
Logic has been added to check against identical properties combination in Pixel Size Calibration.
> Fix issue #818

- mmstudio/src/main/java/org/micromanager/internal/dialogs/ConfigDialog.java
To fix issue #952, override x button in Pixel Preset Editor to make it have same behavior as Cancel button.
> Override x button in Pixel Preset Editor.

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/MagellanViewer.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanGUIAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/surfacesandregions/SurfaceInterpolator.java
Fixes #959
"AcqEngJ" rev="0.6.9"
"NDTiffStorage" rev="1.0.0"
"PycroManagerJava" rev="0.8.20"
> Magellan: bug fixes + add unique identifieer to NDTiffStorage

- buildscripts/ivy.xml
> bump versions

- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ImageCollection.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/MultiChannelShadingMigForm.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingProcessor.java
There still are many strange things happening, and thorough refactoring
would be wonderful.  Will be quite a bit of work though. This change
makes it possible to process data acquired on one system on another
system (will need a configuration with matching channelgroup and preset
names). Fixes bug not being able to remove flatfield.
Changing settings in the plugin while a Processor is in use will not
change the actions of that processor. This seems a bug to me, but needs
significant refactoring to fix, too much work for now.
Closes #968
> MultiChannelShading: Improve logic in the plugin,

- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
- mmstudio/src/main/java/org/micromanager/internal/utils/ColorEditor.java
Fix the bug that color is not updated before the channel is added to `channel_`.
Fix the logic to process click on `edit` button(the color bar in the 6th column) and `ok` button.
> Fix issue#965.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AffineEditorPanel.java
- mmstudio/src/main/java/org/micromanager/internal/pixelcalibrator/PixelCalibratorDialog.java
Replace 2*2 affine transformation table with 3*3.
> Fix issue955.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
> Fix issue988.

- DeviceAdapters/ThorlabsElliptecSlider/ThorlabsElliptecSlider.cpp
- DeviceAdapters/ThorlabsElliptecSlider/ThorlabsElliptecSlider.h
git-svn-id: https://valelab.ucsf.edu/svn/micromanager2/trunk@17381 d0ab736e-dc22-4aeb-8dc9-08def0aa14fd
> ThorlabsElliptecSlider: jdeschamps: Added ELL6_Shutter device

- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/IntensityInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/quickaccess/internal/QuickAccessFrame.java
Histogram rate: Every Image
QuickAccess Panel: Remember 
Closing #994
> Change defaults for histogram update rate and QuickAccess Panel show on startup

- MMCore/CircularBuffer.cpp
> Increase sequence buffer size (frame count) limit

- libraries/Projector/src/main/java/org/micromanager/projector/ProjectorAPI.java
Added because pycro-manager can not (yet) work with static methods.  Can be removed in the future once that limitation has been removed.
> Projector api

- plugins/Tracker/src/main/java/com/imaging100x/tracker/TrackerControl.java
Fix the bug that buttons in Tracker window have no reaction.
> Fix the bug that Tracker can't be closed.

- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionListDlg.java
Stage callbacks contain information about the new stage positions.  The code so far would query all the stages in the list again.  This causes slowdown and in rare cases issues with hardware (see: https://forum.image.sc/t/micro-manager-impossible-to-modify-answertimeout-of-adapter/45319).  Since the event already contains the new position, it seems fine to use that information directly without querying the hardware.
> Studio: No longer query hardware in PositionListDlg upon receiving callbacks.

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
Increase the minimum size of panel at the bottom.
> Fix issue #924.

- libraries/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/DataCollectionForm.java
- libraries/Projector/src/main/java/org/micromanager/projector/internal/ProjectorControlForm.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/InspectorController.java
- mmstudio/src/main/java/org/micromanager/events/ShutdownCommencingEvent.java
- mmstudio/src/main/java/org/micromanager/internal/PropertyEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/CalibrationListDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ConfigDialog.java
- mmstudio/src/main/java/org/micromanager/internal/pipelineinterface/PipelineFrame.java
- mmstudio/src/main/java/org/micromanager/internal/pixelcalibrator/PixelCalibratorDialog.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/TileCreatorDlg.java
- plugins/ASIdiSPIM/src/main/java/org/micromanager/asidispim/ASIdiSPIM.java
- plugins/Assemble/src/main/java/org/micromanager/assembledata/AssembleDataForm.java
- plugins/Gaussian/src/main/java/GaussianTrack_.java
- plugins/HCS/src/main/java/org/micromanager/hcs/HCSPlugin.java
- plugins/MMClearVolumePlugin/src/main/java/edu/ucsf/valelab/mmclearvolumeplugin/CVViewer.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/MultiChannelShadingMigForm.java
- plugins/SnapOnMove/src/main/java/org/micromanager/plugins/snaponmove/MainController.java
- plugins/SnapOnMove/src/main/java/org/micromanager/plugins/snaponmove/SnapOnMovePlugin.java
> Check for cancellation of ShutdownCommencingEvent

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionEngine.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
> Remove an unused and incorrect internal method

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/ImageJBridge.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/MMImageCanvas.java
Make sure the window doesn't expand beyond the screen.
> Fix issue #925.

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
"NDViewer" rev="0.3.0"
"NDTiffStorage" rev="1.1.0"
"PycroManagerJava" rev="0.11.1"
> bump library versions and small magellan change

- DeviceAdapters/TeesnySLM/TeensySLM.cpp
- DeviceAdapters/TeesnySLM/TeensySLM.h
- DeviceAdapters/TeesnySLM/TeensyShutter.cpp
git-svn-id: https://valelab.ucsf.edu/svn/micromanager2/trunk@17403 d0ab736e-dc22-4aeb-8dc9-08def0aa14fd
> fix compiler warnings

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/GUI.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/ExploreAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanGUIAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/surfacesandregions/SurfaceInterpolator.java
"AcqEngJ" rev="0.7.9"
"NDTiffStorage" rev="1.2.0"
"PycroManagerJava" rev="0.12.0"
> Bump library versions and fix Magellan bugs

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
"AcqEngJ" rev="0.8.0"
"NDTiffStorage" rev="1.3.0"
"PycroManagerJava" rev="0.13.0"
> Clean up APIs and use new library versions

- DeviceAdapters/Aladdin/Aladdin.cpp
- DeviceAdapters/LeicaDMI/LeicaDMI.cpp
- DeviceAdapters/LeicaDMI/LeicaDMIModel.cpp
- DeviceAdapters/LeicaDMI/LeicaDMIScopeInterface.cpp
- DeviceAdapters/Utilities/Utilities.cpp
- DeviceAdapters/Utilities/Utilities.h
- MMDevice/DeviceBase.h
- MMDevice/MMDevice.h
Aladin, Utilities, also makes LeicaDMI same between 1.4 and 2.0.
C++ layers of 1.4 and 2.0 should now be identical again. Please keep it that way until we decide this is no longer needed.
> Svn update

- mmstudio/src/main/java/org/micromanager/internal/DefaultApplication.java
Fix an issue introduced in #1061
> fix improper calls to MMStudio.updateGui

- buildscripts/ivy.xml
- plugins/Gamepad/build.xml
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/AsiGamepad.java
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/AsiGamepadFrame.java
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/AxisTable.java
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/ButtonActions.java
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/ButtonTable.java
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/FileCellEditor.java
Also stores and restores current settings from profile.
Tested with a wireless XBox controller, and seems to work.
> Gamepad: ported from 1.4

- mmstudio/src/main/java/org/micromanager/internal/ConfigGroupPad.java
When a user changes a config group the `ConfigGroupPad.setValueAt` method first queries all properties associated with any config group in order to see if the user's action has caused any other config groups to change, it then calls the `studio.app().updateGUI()` method which involved a full update of the cached property values.
This PR changes `ConfigGroupPad.setValueAt` so that it starts by explicitly requesting an update of the property cache. It then uses the cached values for both updating the GUI and for checking if config groups have changed. This means that the same properties don't need to be requested from the hardware twice.
> Reduce querying of property values when changing a config group.

- DeviceAdapters/TriggerScopeMM/TriggerScopeMMTTL.cpp
git-svn-id: https://valelab.ucsf.edu/svn/micromanager2/trunk@17416 d0ab736e-dc22-4aeb-8dc9-08def0aa14fd
> TriggerScopeMM: Fix bad logic in handling GateOpen

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
> Studio: Fix zooming display on second display

- mmstudio/src/main/java/org/micromanager/internal/MMUIManager.java
Should be removed after properly handling issue #1090
> Studio: enable direct manipulation of current PositionList.

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/ExploreAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanAcquisitionsManager.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanGUIAcquisition.java
"AcqEngJ" rev="0.9.0"
"NDTiffStorage" rev="1.6.1"
"PycroManagerJava" rev="0.14.1"
> Bump library versions

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/OMEMetadata.java
> Studio: attempt to create valid OME-XML. Suggested by Jackson Maxfield Brown

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/ExploreAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/LoadedAcquisitionData.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanGUIAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanMD.java
"AcqEngJ" rev="0.10.0"
"NDViewer" rev="0.4.0"
"NDTiffStorage" rev="2.0.0"
"PycroManagerJava" rev="0.16.0"
> Magellan changes and library updates for new version of NDTiffStorage

- autofocus/buildscripts/OughtaFocus.xml
Fixes a build error with PR  #1098.
Just needed to add the new source directory to the build.xml
> Fix oughtafocus build

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/MagellanViewer.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
"AcqEngJ" rev="0.11.0"
"NDTiffStorage" rev="2.1.0"
"PycroManagerJava" rev="0.17.0"
> Bump libs to fix magellan bugs and seq Acq bugs

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDataManager.java
"NDTiffStorage" rev="2.1.7" 
"PycroManagerJava" rev="0.17.1"
> Bump libraries

- buildscripts/ivy.xml
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/ExploreZSliders.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/ExploreAcquisition.java
AcqEngJ" rev="0.12.0"
"PycroManagerJava" rev="0.18.2"
> fix region specific string parsing in magellan and libraries

- buildscripts/ivy.xml
"PycroManagerJava" rev="0.18.3"
"NDTiffStorage" rev="2.3.0"
"NDViewer" rev="0.5.0"
> fix RGB ordering

- DeviceAdapters/Spinnaker/SpinnakerCamera.cpp
git-svn-id: https://valelab.ucsf.edu/svn/micromanager2/trunk@17457 d0ab736e-dc22-4aeb-8dc9-08def0aa14fd
> Spinnaker: added statement missed in the merge

- buildscripts/ivy.xml
"NDTiffStorage" rev="2.4.0"
"PycroManagerJava" rev="0.21.0"
> update library versions

- mmstudio/src/main/java/org/micromanager/data/internal/PropertyKey.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageSinglePlaneTiffSeries.java
- mmstudio/src/main/java/org/micromanager/display/internal/RememberedDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultAlbum.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
Remarkable how many bugs had slipped into MDA settings saving and the use of colors in Album and live/snap display.  These were all regressions, which clearly demonstrates the need for better maintained tests.  Closes #1164, #1131
> Display fixes

- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
> Studio: Suspend live mode when refresh button is pressed

- README.md
Replaces URLs with hyperlinks.
Uses a numbered list for sequential instructions.
Provides links to other repository files that are mentioned.
> Minor improvements to readme formatting.

- .gitmodules
This pull request updates the "mmCoreAndRepositories" submodule to the newest version.
- The SecretDeviceAdapters submodule has had a "svnSync" branch added which will be used to track the history of the SVN repository.
- The "main" branch of the secretdeviceadapters submodule is now up to date.
- default branches have been set for all submodules.
> Submodule updates

- .github/workflows/updatePrivateMain.yml
This action will merge `master` into `privateMain` every time a new commit is pushed to `master`.
> Add a github action to keep branches synchronized

- buildscripts/ivy.xml
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
"AcqEngJ" rev="0.12.1"
"NDViewer" rev="0.5.1"
"PycroManagerJava" rev="0.21.2"
> Bump pycro-manager libraries to add core logging to ZMQ server

- mmstudio/src/main/java/org/micromanager/display/internal/animate/AnimationController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/MDScrollBarPanel.java
> Studio: Fix recently introduced bug red animation lock no longer working as expected.

- mmstudio/src/main/java/org/micromanager/data/DatastoreFrozenException.java
- mmstudio/src/main/java/org/micromanager/data/DatastoreRewriteException.java
- mmstudio/src/main/java/org/micromanager/data/ImagesDifferInSizeException.java
- mmstudio/src/main/java/org/micromanager/data/internal/ImageSizeChecker.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageSinglePlaneTiffSeries.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
> Adds ImagesDifferInSizeExceptions thrown by Storage implementations.

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/FileSet.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/OMEMetadata.java
> Throw exception when MultiPageTiff writer encounters data order that it can not save correctly.

- mmstudio/src/main/java/org/micromanager/data/internal/StorageSinglePlaneTiffSeries.java
> Studio: Fix recently introduced bug naming single page tiff files.

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
- mmstudio/src/main/java/org/micromanager/internal/utils/ProgressBar.java
ProgressBar will need to be re-done as it now makes calls to Swing from non-EDT threads.
> Studio: increase time out before showing Progress Bar

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/DefaultAcquisitionEndedEvent.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDatastore.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageSinglePlaneTiffSeries.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/FileSet.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffWriter.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
- mmstudio/src/main/java/org/micromanager/display/AbstractDataViewer.java
- mmstudio/src/main/java/org/micromanager/display/internal/animate/AnimationController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/ImageJBridge.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/MMImageCanvas.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/GearButton.java
- mmstudio/src/main/java/org/micromanager/display/internal/imagestats/StatsComputeQueue.java
- mmstudio/src/main/java/org/micromanager/display/internal/link/LinkManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/link/internal/DefaultLinkManager.java
Reduces memory consumption significantly, since many large objects are now garbage collected.  Still a long way to go.  Requesting reviews to get input on the best strategy to proceed.  Merging now, since we will need this for our experiment tomorrow;).
> Memory leak fixes

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelCellEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
> MDA Dialog usability fixes

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDatastore.java
> Fixes wrong value returned by getNextIndex in DefaultDatastore for missing Axes.

- mmstudio/src/main/java/org/micromanager/internal/diagnostics/ProblemReport.java
- mmstudio/src/main/java/org/micromanager/internal/diagnostics/gui/ControlPanel.java
- mmstudio/src/main/java/org/micromanager/internal/diagnostics/gui/InitialControlPanel.java
- mmstudio/src/main/java/org/micromanager/internal/diagnostics/gui/LogCaptureControlPanel.java
- mmstudio/src/main/java/org/micromanager/internal/diagnostics/gui/ProblemDescriptionPanel.java
- mmstudio/src/main/java/org/micromanager/internal/diagnostics/gui/ProblemReportController.java
- mmstudio/src/main/java/org/micromanager/internal/diagnostics/gui/ProblemReportFrame.java
- mmstudio/src/main/java/org/micromanager/internal/diagnostics/gui/SendReportControlPanel.java
Also makes the code CheckStyle conformant.
> Fixes a crash in Micro-Manager when the Problem Report is too large to be read into memory.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
Plus Checkstyle cleanup of MMAcquisition.
> More logical display of number of acquired images.

- mmstudio/src/main/java/org/micromanager/internal/utils/performance/PerformanceMonitor.java
so that poeple other than Mark will have chance at understanding what to do with this code.
Closes Issue #1249
> Studio: Add github discussion to PerformanceMonitor,

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
> Fixes issue opening Virtual stacks of large dataset that contain multiple channels

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
> Studio: prevent possible deadlock on exit.

- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/ChannelIntensityController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/ColorModeCell.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/HistogramView.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/ImageStatsPublisher.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/IntensityInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/IntensityInspectorPanelPlugin.java
> Fixes bug with initial rate of histogram update rate in a fresh profile.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
To avoid motion blur seen with ASI stage.
> Studio: Add extra wait after move before snapping.

- mmstudio/src/main/java/org/micromanager/internal/utils/DaytimeNighttime.java
Closes #393.  Only took 5 years;)
> Caret adpats color to display mode

- plugins/CRISP/src/main/java/com/asiimaging/crisp/CRISPFrame.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/CRISPPlugin.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/UserSettings.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/data/Defaults.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/data/Ranges.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/CRISP.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/CRISPSettings.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/SpinnerPanel.java
This spinner exposes another property of CRISP that is available on Tiger firmware version 3.38.
> CRISP: added a spinner to control update rate

- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
- mmstudio/src/main/java/org/micromanager/internal/propertymap/DefaultPropertyMap.java
Partially addresses #1311.  Also fixes some ugly looking main window when the user makes it very large (which people seem to like doing).
> Fixes one deadlock observer while exporting to ImageJ

- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
See: https://forum.image.sc/t/frozen-datastore/61922/2
> Studio: Fix rare bug with frozen Datastore in SnapLiveManager

- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/AsiGamepad.java
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/AsiGamepadFrame.java
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/AxisTable.java
- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/Icons.java
Added a basic API to get and set the multiplier for buttons in the axis assignment table. Also fixed some issues with saving and setting values. The plugin needs to be open to gain access to the axis table so that API methods can work.
> Added a basic Gamepad API

- plugins/Gamepad/src/main/java/com/asiimaging/asi_gamepad/GamepadAPI.java
> Added GamepadAPI.java

- buildscripts/fetchdeps.xml
- buildscripts/ivy.xml
- buildscripts/ivysettings.xml
Pick up Java dependency cleanup.
> Merge main into vs2019

- doc/how-to-build.md
More to do, but closer to current reality.
> Update build instructions

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
> Studio: Implements DisplayWindow.setFullScreen(bool)

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffWriter.java
> Modified MultipageTiffWriter to split large stacks more intelligently.

- mmstudio/src/main/java/org/micromanager/internal/hcwizard/Device.java
Very few changes were needed to make that happen.
> Studio: HCW now displays ranges for Properties with limits.

- doc/how-to-build.md
Puts them all together in one place so it's easier, also added using conda-forge for getting swig rather than compiling it yourself.
> Add more complete ubuntu build instructions

- mmstudio/src/main/java/org/micromanager/internal/PropertyEditor.java
Addresses issue #1409.  requesting review, since I may be overseeing certain cases where this is not a good approach.
> Setting a camera value in the PropertyEditor will now pause live mode

- buildscripts/ivy.xml
Fixes data opening in Magellan @nicost
> Bumo NDTiff version

- mmstudio/src/main/java/org/micromanager/internal/hcwizard/ConfigGroup.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/ConfigWizard.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/DelayPage.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/DeviceSetupDlg.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/PropertyTableModel.java
Closes #1455. 
Previous work on the HCW forgot to re-add the correct column renderer and editor.  Also adds some Javadoc and bit of code cleanup.
> Hcw pre init fix

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
> Studio: make sure that cameraTimeoutMs stays what the user asked for.

- mmstudio/src/main/java/org/micromanager/data/DataManager.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataManager.java
> add missing NDTiff API methods

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
> Studio: Fixes error viewer stopping to respond when images are missing and overlays are shown.

- plugins/Gaussian/src/main/java/edu/ucsf/valelab/gaussianfit/MainForm.java
> A few more corrections akin to #1527

- plugins/CRISP/src/main/java/com/asiimaging/crisp/data/Ranges.java
- plugins/CRISP/src/main/java/com/asiimaging/devices/crisp/CRISP.java
- plugins/CRISP/src/main/java/com/asiimaging/devices/crisp/PropName.java
This is the limit in the firmware.
> CRISP: max value of Number of Averages is 8

- plugins/ASIRingTIRF/src/main/java/com/asiimaging/tirf/TIRFControlPlugin.java
- plugins/ASIRingTIRF/src/main/java/com/asiimaging/tirf/model/TIRFControlModel.java
- plugins/ASIRingTIRF/src/main/java/com/asiimaging/tirf/ui/TIRFControlFrame.java
- plugins/ASIRingTIRF/src/main/java/com/asiimaging/tirf/ui/utils/BrowserUtils.java
Add better error ui and also use the device library to detect the Tiger controller instead of just the device name.
> ASIRingTIRF: update error ui and add better Tiger controller detection

- plugins/Magellan/src/main/java/org/micromanager/magellan/api/MagellanAPI.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/ExploreControlsPanel.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/ExploreAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/LoadedAcquisitionData.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanAcquisitionsManager.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDatasetAndAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanGUIAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/misc/Log.java
Fixes Checkstyle errors from latest PR merge.
> Magellan: Checkstyling latest Magellan changes.

- .pre-commit-config.yaml
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/CoordsComparator.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorException.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPlugin.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginExecutor.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginFrame.java
Noticed this when the Fiji stitcher created stitches with the number of z planes present in the original data.
> Z projector: Removes projected Axis from SummaryMetadata: Bugfix.

- mmstudio/src/main/java/org/micromanager/internal/positionlist/TileCreatorDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/utils/TileCreator.java
Implements feature request by Thomas Julou: https://forum.image.sc/t/creating-positions-along-a-line/73814
> Studio: Add Line method to TileCreator.  Full implementation.

- .pre-commit-config.yaml
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorException.java
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorExecutor.java
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorPlugin.java
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorPluginFrame.java
Also apply Checkstyle rules so that this plugin can also be automatically checked.
Closes #1558.
> Duplicator: Copy over the correct channeldisplaysettings.

- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginExecutor.java
wrong axis interpretation in ImageJ.
> ZProjector plugin: fix bug in axis meatadata that resulted in

- mmstudio/src/main/java/org/micromanager/internal/script/LeftFrameDropListener.java
- mmstudio/src/main/java/org/micromanager/internal/script/ScriptPanel.java
- mmstudio/src/main/java/org/micromanager/internal/script/TopRightFrameDropListener.java
> Studio: Add drag and drop to Script Editor.

- mmstudio/src/main/java/org/micromanager/display/ImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/DefaultImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/ExportMovieDlg.java
- mmstudio/src/main/java/org/micromanager/internal/utils/FileDialogs.java
ExportMovie now can write labels in the file names. These should make it much easier to work with exported images. Cleaned up the code a bit while I was at it.
Closes #1588
> Image exporter now can include labels in the file names.

- plugins/HCS/src/main/java/org/micromanager/hcs/CustomSettingsFrame.java
- plugins/HCS/src/main/java/org/micromanager/hcs/HCSAbout.java
- plugins/HCS/src/main/java/org/micromanager/hcs/PlatePanel.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
Closes #1594.  Still missing the last option, but that is likely better implemented in the PositionList Dialog.
> HCS usability updates

- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/ExportMovieDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
- plugins/HCS/src/main/java/org/micromanager/hcs/CalibrationFrame.java
- plugins/HCS/src/main/java/org/micromanager/hcs/CustomSettingsFrame.java
- plugins/HCS/src/main/java/org/micromanager/hcs/HCSAbout.java
- plugins/HCS/src/main/java/org/micromanager/hcs/HCSException.java
- plugins/HCS/src/main/java/org/micromanager/hcs/HCSPlugin.java
- plugins/HCS/src/main/java/org/micromanager/hcs/NoSuchStageException.java
- plugins/HCS/src/main/java/org/micromanager/hcs/ParentPlateGUI.java
- plugins/HCS/src/main/java/org/micromanager/hcs/PlatePanel.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SBSPlate.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
StageControl: make JTextFields to set the stepsize wider, and right align them (as they display numbers).  Beautify the HCS plugin code.
> StageControl and HCS plugins

- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionListDlg.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
Also contains commits adding, then removing a function to the PositionList Dlg.  Some code was cleaned up in the process.,
> HCS: remember overwrite-append mode

- buildscripts/ivy.xml
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/MDAAcqEventModules.java
- mmstudio/src/main/java/org/micromanager/data/internal/ndtiff/NDTiffAdapter.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/MagellanOverlayer.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/MagellanViewer.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/ExploreAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/LoadedAcquisitionData.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanDatasetAndAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanGUIAcquisition.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanMD.java
Including bumping library versions and changes to Magellan
> Support new features of AcqEngJ

- plugins/HCS/src/main/java/org/micromanager/hcs/SBSPlate.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
This should work for both circular and square wells.  May need fine tuning for edges.
> HCS plugin: ensure that all sites are within the well.

- buildscripts/ivy.xml
> Update pycro-Manager and dependencies

- mmstudio/src/main/java/org/micromanager/display/DisplayWindow.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
> Studio: Implement autostretch method in display-DisplayWindow

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
Downside is that starting the ZMQ server takes even more time.  Should we run this on a separate thread?
> Studio: add more plugins to the ZMQ server search path.

- mmstudio/src/main/java/org/micromanager/display/ImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/CopyAsDisplayed.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/DefaultImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/ExportMovieDlg.java
- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
- mmstudio/src/main/java/org/micromanager/internal/utils/MMKeyDispatcher.java
Reverts micro-manager/micro-manager#1674, seems the most straight forward way to get this merged. Closes #1667.
> Revert "Revert "Added option to copy to the system clipboard to the export images as displayed gear menu.""

- buildscripts/installer_Windows.iss
Addresses https://github.com/micro-manager/mmCoreAndDevices/pull/341#issuecomment-1522546315.
> Add MeadowlarkLC CSV file to installer

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
Change default from false to true. Should only affect new installations.
> Studio: Save metadata.txt by default.

- mmstudio/src/main/java/org/micromanager/internal/menus/WindowMenu.java
De-iconify it before showing.  Otherwise, nothing will hapenn.
> Studio: When selecting a minimized Window in the Windows menu,

- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/navigation/NavigationInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/navigation/NavigationInspectorPanelPlugin.java
> Navigation inspector panel, browse viewers using number and/or text.

- buildscripts/ivy.xml
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJMDADataSink.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/MDAAcqEventModules.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/OptionsDlg.java
More testing is needed, but this is on the way to actually working.  Code also contains additions to make it easy to write the code to use different channel/slice settings at different positions (a feature we have wanted for more than a decade).
Work in progress, do not merge yet (I thought there was a way to set that in the PR, but I can not find it now).
> Improvements to AcqEngJ bridge that are tested on a microscope

- plugins/HCS/src/main/java/org/micromanager/hcs/CalibrationFrame.java
- plugins/HCS/src/main/java/org/micromanager/hcs/ParentPlateGUI.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
> HCS: add load-save option for calibration. 

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
Catches an error I encountered in the wild.  May be smoothing out another, more fundamental error, but at least makes it possible to read this data (which, remarkably enough, is being opened with virtual option).
> Makes MultiPage TIFF reader more robust.

- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/MagellanMouseListener.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanAcqUIAndStorage.java
> fix magellan dataset opening

- mmstudio/src/main/java/org/micromanager/display/DisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/ChannelIntensityController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/IntensityInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/display/internal/imagestats/ImageStatsProcessor.java
- mmstudio/src/main/java/org/micromanager/display/internal/imagestats/IntegerComponentStats.java
- mmstudio/src/test/java/org/micromanager/display/internal/imagestats/ComponentStatsTest.java
> Adds option to exclude pixels with value zero from histogram autostretch and stats.

- mmstudio/src/main/java/org/micromanager/display/internal/RememberedDisplaySettings.java
for most channel groups in add Preset dialog. Closes #1720.
> Studio: Fix for Quick Access Panel bug: not showing presets

- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanAcqUIAndStorage.java
Needs new versions from: https://github.com/micro-manager/pycro-manager/pull/627
> Allow explore acquisition to zoom before data

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultAnnotation.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/navigation/NavigationInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/internal/propertymap/DefaultPropertyMap.java
SummaryMetadata, enormously improving performance with virtual data sets. Also catches several issue with data in read-only locations. Closes #1727
> Studio: navigation panel: Now read positions from

- plugins/HCS/src/main/java/org/micromanager/hcs/PlatePanel.java
Now any XY stage movement that causes events will update the position indicator in the HCS plugin.
> HCS: use event to update position indicator.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/multimda/acqengj/MultiAcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionListDlg.java
Also adds the "from Image" button to the PositionList Dialog to read back the PositionList from a dataset.
> Adds PositionList to DatasetSummary

- mmstudio/src/main/java/org/micromanager/display/ImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/DefaultImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/ExportMovieDlg.java
- mmstudio/src/main/java/org/micromanager/internal/utils/FileDialogs.java
Closes #1801 and closes #1798.
> Image exporter: Adds AVI option, and let's users set name of ImageJ Stack Window

- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/multimda/MDASettingData.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/multimda/MultiMDA.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/multimda/MultiMDAFrame.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/multimda/acqengj/MultiAcqEngJAdapter.java
Closes #1810.  Also improved UI.
> Multi mda: adds option to set a prest before each individual acquisition

- mmstudio/src/main/java/org/micromanager/internal/MMROIManager.java
Closes #1814.  Tested with a Point Grey camera, using combinations of mirroring and rotation.  Did not fully test setting ROIs in images in which an ROI was already set.
> Studio: Correct ROI for rotation or flipping.

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataSaver.java
- mmstudio/src/main/java/org/micromanager/data/internal/ndtiff/NDTiffAdapter.java
> Fixes various issues with NDTIff saving

- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
> Studio: Fix Stage Control (left and right arrows where directing the stage in the same direction).

- configure.ac
Cleanup after micro-manager/mmCoreAndDevices#396.
> Remove dead code from configure.ac

- plugins/RatioImaging/src/main/java/org/micromanager/ratioimaging/RatioImagingFrame.java
- plugins/RatioImaging/src/main/java/org/micromanager/ratioimaging/RatioImagingProcessor.java
Fixes several issues in the UI that prevented the plugin from doing what the user thought it would be doing.  Main problem seemed to be that parsing an empty field would prevent other fields from being parsed.  Other improvement is that channels from newly opened images are now added to the channel dropdown.
> RatioImaging: Fixes several issues.

- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
> Studio: addresses ConcurrentModificationException.  Closes #1860.

- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/CopyToImageJItem.java
> Studio: avoid needles dialog box in to imageJ code.

- plugins/Deskew/src/main/java/org/micromanager/deskew/CliJDeskewProcessor.java
> Deskew plugin honor KeppOriginal also in GPU mode. Fixes one potential GPU memory leak.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
> Studio: make sure that prefix in summarymetadata is correct.

- plugins/SnapOnMove/src/main/java/org/micromanager/plugins/snaponmove/MainController.java
(in a synchronized function wait for a thread to join that is blocked on the same lock)
Closes #1881.
> SnapOnMove: avoid a pretty obvious deadlock.

- plugins/Deskew/src/main/java/org/micromanager/deskew/DeskewFactory.java
- plugins/Deskew/src/main/java/org/micromanager/deskew/DeskewFrame.java
Automate setting KEEP_ORIGINAL: when using the process button, it will be set to False, True when running it while acquiring data.
> Deskew: Use degrees instead of radians,

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIKeyListener.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYZKeyListener.java
Also enables automatic image snapping when using keys to move the stage.
> Adds ability to scroll through display windows using the arros keys.

- mmstudio/src/main/java/org/micromanager/internal/positionlist/TileCreatorDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/utils/TileCreator.java
> Tile creator: adds prefix for position labels, and preserves line directionality.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
> Studo-AcqEngJ: ensure autofocus runs at each new XY stage position.

- plugins/AcquireMultipleRegions/src/main/java/org/micromanager/acquiremultipleregions/AcquireMultipleRegionsForm.java
Needed after changes in #1897.
> Fix AcquireMultipleRegions for TileCreator change

- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/overlays/OverlaysInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/overlay/internal/overlays/ScaleBarOverlay.java
Purely usability improvements (hopefully).
> Overlays, fixes default settings for novel Datastores an draws text to sizebars closer to the edge of the image.

- buildscripts/ivy.xml
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/OptionsDlg.java
Removes it from pycro-manager and creates a new project, [PyJavaZ](https://github.com/PyJavaZ/PyJavaZ) containing the ZMQ bridge. This adds the new dependency PyJavaZ.jar
> Refactor Java-Python bridge into its own project

- plugins/Magellan/src/main/java/org/micromanager/magellan/api/MagellanAPI.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/explore/ChannelGroupSettings.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/gui/GUI.java
- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanAcquisitionsManager.java
This should make it possible to use the Magellan plugin without the Studio environment, but whether or not that really works should be tested.
> Magellan: factor out studio from Magellan api.  

- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingProcessor.java
Also fixes the flatfield not working as expected with Snap/Live images.
> Fixes issue with MultiChannelFlatfield plugin crashing the UI by producing too many alerts.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
> Studio: Fixes AcqEngJ bug in time to next image display.

- plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/PlotPanel.java
Without unicode, I get build errors on linux
> Use unicode mu for axis title in plot panel

- mmstudio/src/main/java/org/micromanager/data/internal/ndtiff/NDTiffAdapter.java
Not quire sure of the effect on performance.
Closes #1923
> Studio-NDTIff: adds shadow index of Coords to be able to provide Coords missing certain axes. 

- plugins/HCS/src/main/java/org/micromanager/hcs/PlatePanel.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SBSPlate.java
Updates stage positions using Core Callbacks.  Also scales the site and position pointers based on the image size, hopefully reflecting reality.
> HCS plugin: Now finally updates stage position as expected.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
> Make runnables work in the new Acquisition Engine.

- autofocus/buildscripts/OughtaFocus.xml
- autofocus/buildscripts/autofocusbuild.xml
> Autofocus build: dumb way to include all 4 source files into Oughtafocus build.

- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorExecutor.java
> Duplicator: Now copies the StagePositionList correctly.

- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/MultiChannelShadingMigForm.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingTable.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingTableModel.java
Also bit of UI improvements and code cleanup.
> MultiChannel Shading plugin: make it possible to work with no changroup "Default" images

- plugins/HCS/src/main/java/org/micromanager/hcs/CustomSettingsFrame.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SBSPlate.java
> HCS plugin: Adds wellSizeX ad wellSizeY to custom Plate editor.

- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/PLogicControlPlugin.java
Forgot to change the getSubMenu() function to return the correct value.
> Move ASIPlogic Control into Device Control submenu

- plugins/Sharpest/src/main/java/org/micromanager/sharpest/SharpestData.java
- plugins/Sharpest/src/main/java/org/micromanager/sharpest/SharpestPlugin.java
- plugins/Sharpest/src/main/java/org/micromanager/sharpest/SharpestPluginExecutor.java
- plugins/Sharpest/src/main/java/org/micromanager/sharpest/SharpestPluginFrame.java
> Shaprest plugin: Add option to select plane at max value rather than plan at best fit value.

- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/PLogicControlFrame.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/PLogicControlModel.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/PLogicControlPlugin.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/ScriptGenerator.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/ASIPLogic.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/ASITigerBase.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/DeviceBase.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/PLogicCell.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/PLogicIO.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/PLogicState.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/IOCell.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/LogicCell.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/LogicInputRow.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/asigui/Button.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/asigui/ComboBox.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/asigui/Panel.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/asigui/RadioButton.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/asigui/Spinner.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/DeviceTab.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/IOCellsTab.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/LogicCellsTab.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/TabPanel.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/WizardTab.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/utils/FileUtils.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/wizards/SquareWaveConfigPanel.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/wizards/SquareWaveDisplayPanel.java
add two new cell types
save and load json
square wave signal generator on wizards tab
handle edge-sensitive inputs correctly
can't write beyond the number of logic cells in the signal generator
> ASIPlogic Control: new cell types, square wave generator; bug fixes

- mmstudio/src/main/java/org/micromanager/acquisition/internal/testacquisition/TestAcqAdapter.java
No longer re-use a Datastore as it leads to unexpected problems.
> Studio-TestAcquisition: Fixed some weird problems in display.

- mmstudio/src/main/java/org/micromanager/acquisition/ChannelSpec.java
- mmstudio/src/main/java/org/micromanager/acquisition/SequenceSettings.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/ImageJBridge.java
> AcqEngine now always report settings when running acquisition.

- mmstudio/src/main/java/org/micromanager/internal/MMROIManager.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/OptionsDlg.java
> Studio: Add option enable auto-snap after ROI button is pressed.

- plugins/AIDPC/build.xml
- plugins/AIDPC/src/main/java/org/micromanager/aidpc/AIDPCConfigurator.java
- plugins/AIDPC/src/main/java/org/micromanager/aidpc/AIDPCFactory.java
- plugins/AIDPC/src/main/java/org/micromanager/aidpc/AIDPCProcessor.java
- plugins/AIDPC/src/main/java/org/micromanager/aidpc/AIDPCProcessorPlugin.java
Closes #1947. Will need Micro-Manager.org documentation.
> AIDPC plugin. With some Claude assistance.  Needs checking.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/IntroDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/introdialogparts/ComboBoxCellRenderer.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/introdialogparts/ConfigSelectionUIController.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/introdialogparts/ProfileSelectionUIController.java
On WIndows only, as other plastforms use other LAFs and I can not check those easily.
Closes #1741
> Studio-Splash screen: Right align the comboboxes.

- .github/workflows/apidoc.yml
@v2 will soon become unavailable.
> CI: Upgrade actions/cache to @v4

- buildscripts/nightly/nightlybuild_macOS_deps.sh
- buildscripts/nightly/nightlybuild_macOS_mm.sh
Update Boost download URL; fix an incorrect path variable.
> Fixes to macOS build

- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelConfigEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelConfigLighSheetPanel.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelConfigOptimalZPanel.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelPresetEditor.java
Realized the layout was confusing while documenting the changes on the website.
> Studio: Pixel Editor Optimal Z now is in its own panel.

- plugins/ASIdiSPIM/src/org/micromanager/asidispim/AcquisitionPanel.java
fix for interleaved channels overlap camera
> [1.4 ASIdiSPIM] AcquisitionPanel.java

- plugins/ASIdiSPIM/src/org/micromanager/asidispim/Utils/ControllerUtils.java
tweak milestone signal to handle interleaved channels overlap camera mode
> [1.4 ASIdiSPIM] ControllerUtils.java

- plugins/ASIdiSPIM/src/org/micromanager/asidispim/AcquisitionPanel.java
- plugins/ASIdiSPIM/src/org/micromanager/asidispim/XYZGridPanel.java
- plugins/ASIdiSPIM/src/org/micromanager/asidispim/api/ASIdiSPIMImplementation.java
- plugins/ASIdiSPIM/src/org/micromanager/asidispim/api/ASIdiSPIMInterface.java
make sure we are dropping the right images
> [mm1.4] ASIdiSPIM fix for hardware timepoints with interleaved channels

- plugins/Deskew/src/main/java/org/micromanager/deskew/DeskewFrame.java
Complicated ways to prefer the config file value but honor changes.
Closes #1984.  
When there are deficiencies in this approach, please open a new issue (mentioning #1984).
> Deskew plugin: Now uses dy/dz for angle when available.

- mmstudio/src/main/java/org/micromanager/internal/pipelineinterface/PipelineTableModel.java
Possibly avoids issues (I could not reproduce the usual annoyances with this dialog).
> Studio: More correct way to restore pipeline dialog.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJMDADataSink.java
Fixes general issues with Multi-Camera acquisition and specifically a bunch of issues with AcqEngJ.
> Multi camera display

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
caused by having actionlisteners attached while adding entries to the dropdown.
> Studio: MDA Dialog: fix bug in Z drive selection 

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
> Mda dialog fix

- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
Channel exposures when syncing between MDA and main window is on.
I do not understand how this ever could have worked.
> Studio: Fix weird bug resulting in incosistent updates of

- DeviceAdapters/ASITiger/ASIScanner.cpp
matches documentation now which admits the name is misleading...
> mm1.4 ASITiger SetSpotInterval now only changes the exposure time, not the interval

- libraries/Makefile.am
> Jar name was wrong in PluginUtilities build

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/display/DisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/DisplayWindow.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultAlbum.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
- plugins/Deskew/src/main/java/org/micromanager/deskew/DeskewAcqManager.java
where it make much more sense.
> Studio: Moves WindowPositionKey from DisplaySettings to DisplayWindow

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
> Studio: Fixes NPE in MMAcquisition

- mmstudio/src/main/java/org/micromanager/acquisition/internal/testacquisition/TestAcqAdapter.java
- mmstudio/src/main/java/org/micromanager/display/DisplayWindow.java
Also remembers test Acq window position correctly.
> Ensures that Z drive returns to the original position after a Test Acquisition

- mmstudio/src/main/java/org/micromanager/internal/utils/AutofocusPropertyEditor.java
Now reponds to channelgroup changes, and remembers properties that were set better.
> Studio: Nicer UI for autofocus properties.
