- buildscripts/javalibs.xml
This make the micro-manager2 branch compile and not barf on the ASIdiSPIM plugin
> buildscripts: updated math 3 library to the version in 3rdpartypublic

- mmstudio/src/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/org/micromanager/display/internal/DefaultDisplayWindow.java
Thus DefaultDisplayManager's createDisplay method is now a straight
pass-through instead of having significant extra logic in itself. Much cleaner.
> [Display] Move DefaultDisplayWindow factory into that class.

- mmstudio/src/org/micromanager/display/internal/ButtonPanel.java
- mmstudio/src/org/micromanager/display/internal/CanvasUpdateThread.java
- mmstudio/src/org/micromanager/display/internal/ChannelSettings.java
- mmstudio/src/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/org/micromanager/display/internal/DefaultDisplaySettings.java
- mmstudio/src/org/micromanager/display/internal/DefaultDisplayWindow.java
- mmstudio/src/org/micromanager/display/internal/DisplayDestroyedEvent.java
- mmstudio/src/org/micromanager/display/internal/DummyImageWindow.java
- mmstudio/src/org/micromanager/display/internal/GearButton.java
- mmstudio/src/org/micromanager/display/internal/MMCompositeImage.java
- mmstudio/src/org/micromanager/display/internal/MMImageCanvas.java
- mmstudio/src/org/micromanager/display/internal/MMVirtualStack.java
- mmstudio/src/org/micromanager/display/internal/ScaleBarOverlayFactory.java
- mmstudio/src/org/micromanager/display/internal/ScaleBarOverlayPanel.java
- mmstudio/src/org/micromanager/display/internal/ScrollbarAnimateIcon.java
- mmstudio/src/org/micromanager/display/internal/ScrollbarLockIcon.java
- mmstudio/src/org/micromanager/display/internal/ScrollerPanel.java
- mmstudio/src/org/micromanager/display/internal/TimestampOverlayFactory.java
- mmstudio/src/org/micromanager/display/internal/TimestampOverlayPanel.java
Mainly removal of superfluous imports, making variables final whenever possible and avoiding hiding names used in superclass
> mmstudio: cleanup of display-internal code.  

- mmstudio/src/main/java/org/micromanager/internal/pluginmanagement/DefaultPluginManager.java
- mmstudio/src/main/java/org/micromanager/internal/pluginmanagement/PluginFinder.java
Fixes issue #110 and clarifies the behavior of the class loader used by
plugins (once plugin discovery is finished, it is just a URLClassLoader).
> Prevent repeated loading of plugins contained in MMJ_.jar

- autofocus/src/main/java/org/micromanager/autofocus/OughtaFocus.java
- mmstudio/src/main/java/org/micromanager/internal/utils/MathFunctions.java
- mmstudio/src/test/java/org/micromanager/internal/utils/MathFunctionsTest.java
Uncoupled OughtaFocus from internal.MathFunctions.  Also ported MathFunctions from math commons 2 to 3.  Tested with build-in test function.  This class is possibly only used in Projector plugin, in which case it would be moved there. Reason:  I need to use OughtaFocus with the diSPIM and MMClearVolume plugins and want to reduce the dependencies I need to bring into the MMClearVolume project to get it to run under Netbeans. Also, generally useful to get rid of math commons 2 and to reduce dependencies on internal classes.
> Reduced dependency of OughtaFocus on internal components and reduced use of math commons 2

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- Behavior on resizing window was incorrect, now vertical resizing
allows expansion of the channel table.
- Contents of the first 5 panels are now correctly centered.
- Labels are consistently aligned.
- Comments section was completely broken when entering more than a few
lines. Now a scroll bar appears.
- Most of the little spurious layout shifts on resizing have been
eliminated.
- Calitalization has been made consistent.
- Other fine tuning.
> Fix MDA dialog layout

- mmstudio/src/main/java/org/micromanager/display/DisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/ContrastCalculator.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/inspector/HistogramsPanel.java
Add an option to disable the use of the ROI pixels for scaling the intensity of the image displayed. See #262 for discussion.
@ChrisWeisiger I added the option to the histogram panel (not in the gear menu) because I already did it when I saw your message. I like it here but if you want me to move it to the gear menu, I'll do it.
> Add an option to disable the use of the ROI pixels 

- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ImageCollection.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingProcessor.java
The multichannel shading plugin did not work when no ROI was set.  
Due to an error in the code matching the current state to the configuration preset, it could choose the wrong flatfield image.
Both of these bugs are fixed.
> Shading plugin bug fixes

- mmstudio/src/main/java/org/micromanager/internal/script/BeanshellEngine.java
An EvalError was previously degraded to a - general - error, and
the getErrorText() function was used to show feedback to the user.
For whatever reasons, an EvalError has much more useful information
in the getMessage() function.  Therefore the formatBeanshellError
function now uses the getMessage() function to provide feedback to
the user for errors of type EvalError.  This greatly helps scripts writers.
> Script Panel: Better error reporting.

- mmstudio/src/main/java/org/micromanager/display/DisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/ImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/ExportMovieDlg.java
- scripts/ExportImageSequence.bsh
This adds a new API interface `ImageExporter` and its implementation, which can be used to generate a sequence of images-as-rendered in PNG, JPG, and ImageJ stack formats. Effectively it is an API implementation of the logic from the "Export Images as Displayed" menu option in the image display's gear menu (said option now uses the new API).
It also adds a script, ExportImageSequence.bsh, that demonstrates how to use the API.
> Add "export image sequence" functionality to the display API

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/PropertyEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/CalibrationEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ConfigDialog.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/GroupEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PresetEditor.java
- mmstudio/src/main/java/org/micromanager/internal/utils/PropertyTableData.java
- mmstudio/src/main/java/org/micromanager/internal/utils/ShowFlags.java
- mmstudio/src/main/java/org/micromanager/internal/utils/ShowFlagsPanel.java
This adds a text box to the Device Property Browser/Config Group Editor which can be used to find specific properties by searching by name. The search is case-insensitive and can include device names (using the standard "devicename-propertyname" construction).
This change also converts the GUI for those dialogs to use MigLayout instead of SpringLayout, and makes a number of style changes.
I wanted to use the same system for the Pixel Calibration Editor, but unfortunately it uses a different backing data for its property table that isn't compatible with the `ShowFlagsPanel` that the other entities use. Its GUI appears to be a largely copied one-off of the existing GUIs; maybe future work can bring it up to speed. For the time being I've settled for just fixing a longstanding legibility …
> Add "search" filter to Device Property Browser and Config Group Editor

- mmstudio/src/main/java/org/micromanager/internal/script/BeanshellEngine.java
Previously whenever a null pointer exception (npe) happened, the
Beanshell console would report ```line x: general error: null```.
It helps me to know that a npe ocurred, so I changed the code to
report ```line x: Null Pointer Exception```.
> Scrips: Better reporting of Null Pointer Exceptions

- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ImageCollection.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ImageUtils.java
Previous refactoring left out processing of Floatprocessors, which
is needed at runtime.  Also, negative ROIs that now make it though to
this plugin cause problems with image dimensions due to the way they
are handles by the ImageJ setROI function.  Therefore, negative x and y
positions are moved to 0, which works around this porblem, possible at
cost of a slightly offset flatfield (not sure if that is really the case).
> MultiShading plugin: Add missing code and fix negative ROIs.

- mmstudio/src/main/java/org/micromanager/internal/script/BeanshellEngine.java
The code catching a ParseException parses out the line number at which the
parse error happened from the eror message.  It had a hard-coded offset of
20 in the string, hence any error message that had the line number at
a different position would cause an uncaught exception in the Integer.parseInt 
function, and no output to the user.  This change has a somewhat better approach 
(albeit still feeble and easily breakable) to finding the line number.  
A full fix requires fixing the Beanshell code that causes the line numbers to be unreliable.
> Improved error reporting for Beanshell.

- mmstudio/src/main/scripts/org/micromanager/scriptpanel_startup.bsh
The inspect function declared in scriptpanel_startup.bsh no longer
worked and barfed in line 216 in which a null value for the String
value was used.  By setting the variable value to a String "null", this
error is avoided.  It is a bit unclear why the problem occurred to begin
with, but I do not think that warrants the time to figure out an explanation.
> Beanshell startup script, fix for issue with inspect function.

- mmstudio/src/main/java/org/micromanager/PluginManager.java
- mmstudio/src/main/java/org/micromanager/display/DisplayGearMenuPlugin.java
- mmstudio/src/main/java/org/micromanager/display/internal/ButtonPanel.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayWindow.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/ExportImagesItem.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/GearButton.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/LineProfileItem.java
- mmstudio/src/main/java/org/micromanager/internal/pluginmanagement/DefaultPluginManager.java
- mmstudio/src/main/java/org/micromanager/internal/utils/SortedMenu.java
- mmstudio/src/main/java/org/micromanager/internal/utils/SortedPopupMenu.java
This plugin type is used for entries in the gear menu in image display windows.
It is structurally very similar to the MenuPlugin type, but appears in a
different part of the GUI and receives the relevant DisplayWindow in its
onPluginSelected() method.
This also moves SortedMenu out of DefaultPluginManager, and adds a
corresponding SortedPopupMenu class for JPopupMenus.
> Plugins: add DisplayGearMenuPlugin type.

- plugins/HCS/src/main/java/org/micromanager/hcs/CalibrationFrame.java
- plugins/HCS/src/main/java/org/micromanager/hcs/CustomSettingsFrame.java
- plugins/HCS/src/main/java/org/micromanager/hcs/HCSPlugin.java
- plugins/HCS/src/main/java/org/micromanager/hcs/PlatePanel.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
Addresses issue #302.  Calibration can now be executed on any well of the plate.  Either the center of the 
current well can be set directly, or the four edges of the well can be located to define the center of the well (Two edge calibration was not implemented because data on well dimensions may not be accurate and the UI would be more complicated).  
In addition, this code makes it impossible to use the 'Move' mode before calibration (which was a very dangerous operation mode).
> HCS plugin: Implement calibration on any well, and add ability to use the well edges.

- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
and ensure that the code works as expected in different locales.  I had an exception in one of these that somehow caused the application to quit altogether (not sure how that is possible, but it happened).  We have had horrible problems in the past with different locales that were prevented by consistently using the static functions in NumberUtils.  Their use will at the very l;east guarantee consistent interpretation of input of numbers in Micro-Manager.  It may be good at one point to do a search for all "parseDouble" instances and replace them all.
> HCS plugin: Prevent several NumberFormatExceptions

- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorPluginFrame.java
> Duplicator plugin: fix bug in handling of file name only apparent on Windows

- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorPluginFrame.java
Such situations can arise when plugins or scripts generate MM datasets and should be handled gracefully.  There may be more problems like this, but they may be hard to find.
> Duplicator plugin: Fix null pointer exception that occurs when metadata do not contain channel names

- mmstudio/src/main/java/org/micromanager/alerts/internal/AlertsWindow.java
- mmstudio/src/main/java/org/micromanager/display/internal/inspector/InspectorFrame.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
- mmstudio/src/main/java/org/micromanager/quickaccess/internal/QuickAccessFrame.java
- plugins/ASIdiSPIM/src/main/java/org/micromanager/asidispim/ASIdiSPIM.java
- plugins/Gaussian/src/main/java/GaussianTrack_.java
- plugins/HCS/src/main/java/org/micromanager/hcs/HCSPlugin.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/MultiChannelShadingMigForm.java
By listening to this event, these windows will close when shutdown starts and do not rely on a 
System.ext(0) to close.  The plugins that I changed (not all yet), listen to the external event.  It 
may be good to add this function to the MMPlugin interface so that plugin writers realize that they
may want to implements this.
Addresses issue #419
> mmstudio and plugins: Windows now listen for the ShutdownCommencing Event.

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultSummaryMetadata.java
When reading Summary metadata from old datasets, all unknown tags are now stored in UserData rather than being discarded.
Fixes issue #433
> mmstudio: Store unknown summary metadata tags in userData, rather than ignoring them

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultSummaryMetadata.java
- mmstudio/src/main/java/org/micromanager/display/internal/inspector/InspectorFrame.java
- mmstudio/src/main/java/org/micromanager/display/internal/inspector/MetadataPanel.java
For both per-image and summaryMetadata, now shows all userData as key-value pairs where the key is preceded with "userData-".  Note that the capitalization is different for image and summarymetadata, not sure if I caused that and/or that should be normalized.  
This PR include PR #435, which introduced the userdata in the summaryMetadata.
Fixes issue #434
> MetadataPanel: Better display of UserData

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDatastore.java
- scripts/datastoreExample.bsh
Addresses issue #470.  Also fixes broken datastore example script.
> Fixes bug: "closing a datastore does not always close filehandle"

- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorPluginFrame.java
I encountered a situation where the function metadat.getChannelNames() returned fewer names than the number of channels in the datastore.  This was accompanies by an error reading in the file (see below).  Even though this does not fix the underlying cause, this change will make the code more robust (and makes it workable with this specific file).  
[       ] java.io.IOException: Offset header incorrect, expected: 99384722   found: 0 in Thread[Thread-7,6,main]
[       ]   at org.micromanager.data.internal.multipagetiff.MultipageTiffReader.readOffsetHeaderAndOffset(MultipageTiffReader.java:432)
[       ]   at org.micromanager.data.internal.multipagetiff.MultipageTiffReader.readComments(MultipageTiffReader.java:380)
[       ]   at org.micromanager.data.internal.multipagetiff.MultipageTiffRea …
> Duplicator plugin: Fixes problems caused by wrong channelnames in metadata

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
This fixes issue #475 by setting the channelGroup when setAcquisitionSettings is called. I also changed getAcquisitionSettings to return channelGroup even when no channels are selected, because calling setAcquisitionSettings with no channels currently sets useChannels_ to false, so that the channelGroup was not being returned. This better mirrors the behavior of the UI which allows channelGroup to be set with no channels.
> Set channelGroup fix

- libraries/Projector/src/main/java/org/micromanager/projector/internal/ProjectorControlForm.java
The range for the initial (small) small search can sometimes be too large.  This change reduces the range from 10% to 3%.  It would be best to have an automatic way of minimizing the range (for instance by checking whether or not a calibration point was found, and if not, try again closer to the center)
> Projector: Decrease range of initial calibration search

- plugins/FrameCombiner/src/main/java/org/micromanager/plugins/framecombiner/FrameCombiner.java
`FrameCombiner` plugin used java 1.8 only syntax and I think (need to be confirmed) that MM is build with java 1.6. I guess that could cause issues...
This PR revert the syntax to a one compatible with java 1.6.
> Revert java 1.8 only syntax to be compatible with -source 1.6 in FrameCombiner

- plugins/SlideExplorer/src/main/java/org/micromanager/slideexplorer/Display.java
- plugins/SlideExplorer/src/main/java/org/micromanager/slideexplorer/Hub.java
SlideExplorer would always start with the intensity scaling set to an extreme that would make the image appear all white. This change ensures that it is auto-scaled after the first tile is acquired. There may be room for further improvement to the heuristic used to determine intensity range.
> SlideExplorer: Adjust contrast after first tile acquired

- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ImageCollection.java
- plugins/MultiChannelShading/src/main/java/org/micromanager/multichannelshading/ShadingProcessor.java
Flatfield images should be the full size of the camera (i.e., unbinned, no ROI).  So far,
this was not checked, the code simply ran into exceptions.  This change only compares 
the image with the size of the background image.  May need
to compare to the image size of the current camera.  There are certainly
problems in this plugin when using multiple cameras that differ in size.
This change should help make the user realize that there is a problem
and help figure out what that problem may be.
> MultiChannelShading: post an alert when flatfield image is wrong size.

- mmstudio/src/main/java/org/micromanager/display/internal/overlays/ScaleBarPanel.java
- mmstudio/src/main/java/org/micromanager/display/internal/overlays/TimestampPanel.java
- plugins/PatternOverlay/src/main/java/org/micromanager/patternoverlay/PatternOverlayPanel.java
Scalebar no longer disappears on the right side of the image.
Text is centered on top of the scale bar.
Offset settings are interpreted such that placing thr bar in another place does not necitate changing these settings.
UI is improved (it looked raggy and unfinished on Mac OS X, it still may be nice to use more width than height as it currently does).
Addresses issue #542.
> mmstudio ScaleBar improvements.

- mmstudio/src/main/java/org/micromanager/display/internal/inspector/OverlaysPanel.java
- mmstudio/src/main/java/org/micromanager/display/internal/overlays/ScaleBarPanel.java
- mmstudio/src/main/java/org/micromanager/display/internal/overlays/TimestampPanel.java
Replaced KeyListeners with DocumentListeners so that the correct values are stored in the preferences (fixing a problem with very wrong values when re-opening overlays).  Made buttons smaller, similar to buttons used elsewhere in the Inspector window, to reduce the size taken up by Overlay UI.
> Inspector window overlay fixes

- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginExecutor.java
Main reason was that some acquisitions (diSPIM ) saved on disk when
re-opened say that they are not saved (which seems a bug in itself,
but not one that I have time investigate).
> ZProjector: Allow it to work on ongoing acquisitions.

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataManager.java
This PR fixes #551 by checking whether the input argument ends in the file system's separator character. If it does, the trailing character is removed and the method proceeds as before.
> Remove trailing separator characters from argument to getUniqueSaveDirectory

- plugins/Makefile.am
Hopefully this will bring this useful plugin back to the unix distribution.
> ZProjector: add missing entry to Makefile.am.

- mmstudio/src/main/java/org/micromanager/internal/hcwizard/DeviceSetupDlg.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/MicroscopeModel.java
This is a first attempt to fix the shortcomings of the current handling of serial ports I've described [here](https://sourceforge.net/p/micro-manager/mailman/message/36088954/).
The issue is that serial ports were originally designed to handle COM ports only but have since been (ab)used to handle other types of ports. In my specific case of a serial-over-TCP/IP port (I plan to make a separate PR for this once it's finished), I need a way to dynamically add new ports should all the current ones be in use at the moment.
This PR makes it so that each time the Device setup dialog is shown, the libraries are rescanned for new serial ports.
I have tested this with my TCP/IP port which simply registers a new port (with incrementing index) each time the currently last port is initialized and it …
> Reload available serial ports each time DeviceSetupDlg is shown

- mmstudio/src/main/java/org/micromanager/MultiStagePosition.java
Bug reported by Nick Anthony in issue #690.  Values were stored as Integers,
but read back as primitives which failed.  Reading them back in as Integers
fixes this bug and makes it possible to retrieve these data in old stored
positionlists.
> Studio: Correctly reads grid column and row in stored positionlists.

- mmstudio/src/main/java/MMStudioPlugin.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
This PR extends the changes in: https://github.com/nicost/micro-manager/pull/48 so that they can be used when MMStudio is launched from ImageJ rather than only from Matlab.
This adds the ability for a user to pass arguments to micromanager at startup just like you would with any CLI program. 
In the case of launching MMStudio from ImageJ this would be done in an imageJ macro as `run("Micro-Manager Studio", "-profile MyProfileName");` A user could potentially modify the following line  to make this happen as soon as ImageJ is launched: https://github.com/micro-manager/micro-manager/blob/7a37a23f9134a16807a1f6662322d6301588bfd4/bindist/any-platform/macros/StartupMacros.txt#L45
Currently the only option supported is the `-profile {UserProfileName}` option which causes MicroManager to skip …
> Allow specification of default User Profile to skip splashscreen

- mmstudio/src/main/java/org/micromanager/internal/dialogs/IntroDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/OptionsDlg.java
- mmstudio/src/main/java/org/micromanager/profile/internal/UserProfileAdmin.java
Options were still present but not functional.  This PR makes them functional again.  However, I can not makes these options work for the non-default-users.  In addition, it makes sense that only the default user can set these settings, so that is the approach I took.
In general, it would be nice to have a clearly documented mechanism for loading properties that need to be in effect before the profile is loaded/selected.
> Enable by-passing the splash-screen again

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/script/ScriptPanel.java
Previously, because the profile was used before the UserProfile was activated,
and after it was shutdown, settings were read and written to the default
profile most (but not all) of the time. This commit mainly changes the
order during startup, and ensures that settings will not be saved
twice during shutdown (which apparently often runs twice).
> Studio-ScriptPanel: Correctly stores scripts in profile.

- MMDevice/DeviceUtils.cpp
- MMDevice/DeviceUtils.h
Python 3.5 and 3.6 for Windows, in their pyconfig.h, define a macro
'timezone', which breaks DeviceUtils.h.
We cannot easily remove struct timezone and gettimeofday() (they are
used by multiple device adapters), so allow conditional disablement for
now.
This has no effect on device interface version (no ABI change).
> MMDevice: allow conditional disable for 'timezone'

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultImageJConverter.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/CopyToImageJItem.java
Previously, a null pointer would be prevent export of datastores that
had missing images.  The new code will fill in these missing Images
with empty images of the same dimensions as type as the other
images in the datastore.
> Studio: Exports to ImageJ even when images are missing from a datastore

- plugins/ZProjector/src/main/java/org/micromanager/zprojector/CoordsComparator.java
Projecting a large data set that misses data in the last time point.
This caused the problem descibed in issue #716.  By changing the order
of Coords, such that the time axis is worked on last, results in
saving the data correctly.  I am not absolutely sure that other
orders do not work (will test), and clearly, the current solution
only works when missing data at the end of the time axis, not of
other axes.
> ZProjector: work around bug in Multi-Page Tiff saving code.

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/RGBColorModeStrategy.java
Addresses issue #729.  Problem was caused by Imagej code setting stack
to null when stacksize is 1.  This was correctly addressed in ImageJBirdge,
but the same problem arose in RGBColorModeStrategy.  Fixed here.
> Studio: display MDA of RGB images correctly.

- plugins/Emu/src/main/java/de/embl/rieslab/emu/ui/ConfigurablePanel.java
- plugins/Emu/src/main/java/de/embl/rieslab/emu/ui/swinglisteners/SwingUIListeners.java
- plugins/Emu/src/main/java/de/embl/rieslab/emu/ui/uiproperties/MultiStateUIProperty.java
- plugins/Emu/src/main/java/de/embl/rieslab/emu/ui/uiproperties/SingleStateUIProperty.java
- plugins/Emu/src/main/java/de/embl/rieslab/emu/ui/uiproperties/TwoStateUIProperty.java
- plugins/Emu/src/main/java/de/embl/rieslab/emu/ui/uiproperties/UIProperty.java
- plugins/Emu/src/test/java/de/embl/rieslab/emu/micromanager/mmproperties/MultiStateUIPropertyTest.java
- plugins/Emu/src/test/java/de/embl/rieslab/emu/micromanager/mmproperties/SingleStateUIPropertyTest.java
- plugins/Emu/src/test/java/de/embl/rieslab/emu/micromanager/mmproperties/TwoStateUIPropertyTest.java
- plugins/Emu/src/test/java/de/embl/rieslab/emu/micromanager/mmproperties/UIPropertyTest.java
* Update EMU to 8e527f
* New methods in ConfigurablePanel and UIProperty subclasses
* These methods avoid state value-index collisions
* These methods are called in SwingUIListeners
> Provides mechanism to avoid state value-index collisions in EMU

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/MMVirtualStack.java
As discussed in previous PR.  We can change this again in the future, but for now this will protect our images from accidental changes in ImageJ.
> Studio: duplicates pixels before handing them to ImageJ.

- mmstudio/src/main/java/org/micromanager/internal/DefaultAlbum.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
Fixes bug reported in issue #425:
Snap to Album
Close All, choose no prompts
Snap to Album again (nothing appears)
DefaultAlbum now listens to display events.  When its display
closes, it now sets its reference to the Datastore to null,
prompting additions to the Album re-open a new datastore and
display.
> Studio: Album can be used again after Close All was chosen.

- mmstudio/src/main/java/org/micromanager/display/inspector/internal/InspectorController.java
Otherwise, closing an Inspector will lead to an exception on application exit.
> Studio: unregister closing Inspector from eventbus.

- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
- When snapping images, the number of channels in the display now always matches the number of camera-channels of the current camera.
- Channel-names in the Inspector now match the channel-names in the viewer.
- Channel-names now are the same as those generated by the acquisition engine (i.e. "channel-camera" rather than "channel camera", and no space in front of camera if no channel matches).
> Dual camera fixes multiple issues

- mmstudio/src/main/java/org/micromanager/events/internal/CoreEventCallback.java
Rather than selecting only the stagepositionchanged events for the core-focus drive, all such events are relayed on the Eventbus and listeners should select the drive they are interested in. Same change
was made for the XYStage callback.  Reasons for this restriction in the code were unclear as all listeners (StaticInfo and StageControlFrame) were already checking the drive name.
> Studio: CoreEventcallback relays all StagePositionChanged events.

- mmstudio/src/main/java/org/micromanager/events/internal/CoreEventCallback.java
To avoid a callback running on the EDT to immediately callback into the core, which could result in more callbacks, always call invokeLater, even when the callback already runs on the EDT.
This allows the current callback to finish, and the code now running on our eventbus to be completely separated.
> Studio: CoreEventCallback always calls invokelater.

- mmstudio/src/main/java/org/micromanager/internal/navigation/XYNavigator.java
Code doing orientation correction wants input in pixels rather than
microns, resulting in movement multiplied by pixel size rather than the
amount enetered in the StageControl Plugin.  Orientation correction is
still carried out, but now input x and y movements are first expressed
as pixels, resulting in correct values.
Addresses issue #760.
> Studio: Bug fix for key-press movements not moving stage as expected.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/display/ChannelDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/ColorModeCell.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultChannelDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/RememberedChannelSettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/RememberedSettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
Addresses issue #752. Both MMAcquisition and the Snap/LiveManager now pull the channel colors
from the static methods in RememberedSettings.  This unifies the channel
colors except for the ones shown in the MDA.  We could either remove the
channel colors in the MDA dialog altogether, update them whenever the
colors of the Snap/Live window are updated, or leave things as they are now,
This laso created the opportunity to update more than just the colors.
However, I like to keep those separate between Snap/Live and acquisition,
since I can imagine many situation where you do not want one to influence
the other. Todo: evaluate how this affects displays created through the
scripting api.
> Studio: Channel colors unified in RememberedSettings.

- mmstudio/src/main/java/org/micromanager/acquisition/ChannelSpec.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffWriter.java
- mmstudio/src/main/java/org/micromanager/display/internal/RememberedSettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/events/internal/ChannelColorEvent.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelCellEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
- mmstudio/src/main/java/org/micromanager/internal/utils/ColorEditor.java
- mmstudio/src/main/java/org/micromanager/quickaccess/internal/controls/PresetButton.java
Synchronizes channels colors in the application.  Changing the color of the live/snap window (if it shows the image of a channel) will update the corresponding color in the MDA dialog (and vice versa).  Adds channelgroup to ChannelSpec class (which is in the API, hence this is an API update).
> Manages colors associated with channels. Closes #769

- mmstudio/src/main/java/org/micromanager/data/internal/PropertyKey.java
Encountered in the wild: metadata containing position, z, time, channel as
Coord keys.  This may be a bug, but I am not aware of a downside of
accepting these, and this change at least makes those data accessible
again to people.
> Studio: Fix reading single TIFFS with broken metadata.

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/MMPositionListDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/MMStudioPositionListDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionListDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionTableModel.java
The current implementation of `PositionListDlg`  operates under the assumption that there will be only one instance of it. It fires `NewPositionListEvent`s to the MMStudio `EventManager` and it updates the `AcquisitionControlDlg` whenever a change is made to the `PositionList`.
However there are scenarios where someone may want to make use of one or multiple `PositionListDlg`s to generate or edit a `PositionList` without wanting to have any effect on the `EventManager` or the `AcquisitionControlDlg`
This PR removes the functionality that relies on only having one instance from the `PositionListDlg` and moves it to a new subclass called `MMPositionListDlg`
The end result is that the behavior of the base Micro-Manager program are completely unchanged while readability is improved. However …
> Allow multiple PositionListDlg

- MMCoreJ_wrap/mvnDeploy.bsh
- MMCoreJ_wrap/pom.xml
- MMCoreJ_wrap/src/main/java/mmcorej/org/json/HTTP.java
- MMCoreJ_wrap/src/main/java/mmcorej/org/json/JSONObject.java
- MMCoreJ_wrap/src/main/java/mmcorej/org/json/XML.java
- MMCoreJ_wrap/src/main/java/mmcorej/org/json/XMLTokener.java
- buildscripts/ivy.xml
- buildscripts/ivysettings.xml
Adds pom.xml in MMCodeJ_wrap that can be used to build MMCoreJ as a mavenized jar and deploy to dl.bintray.com/micro-manager.  Needs strict discipline to increase version numbers and re-run using maven whenever version is changed.  Needs automation in the near future.
> Mavenized distribution of MMCoreJ_wrap

- mmstudio/src/main/java/org/micromanager/display/DisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
deprecates overloaded Datastore version.
> Studio: Ads DisplayManager.getDisplay(DataProivder) and

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataManager.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultImageJConverter.java
Converts ImageJ ColorProcessors back to Micro-Manager RGB32 images.  Converting back and forth is very inefficient, so should be avoided. Fixes issue #820
> Studio: convert RGB ImageJ imaged back to MM format correctly

- mmstudio/src/main/java/MMStudioPlugin.java
The implementation of the ImageJ `MMStudioPlugin` allows specifying a user a profile to automatically start using a macro option. However the `ij.Macro.getOptions()` function needs to be run from the same thread as the `run` method of the plugin. This was not being done and so the macro options were not being received. Now this is fixed.
> Fix bug with MMStudio startup arguments when running as ImageJ plugin

- Tutorial/Tutorial4/Tutorial4.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
- mmstudio/src/main/java/org/micromanager/internal/menus/ToolsMenu.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/CenterAndDragListener.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/UiMovesStageManager.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYZKeyListener.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/ZWheelListener.java
Main issue was that a manager and the listeners themselves were listening for changes in mousemovesstage state.  Now, the listeners are always active, and the manager removes listeners when mousemovesstage is switched off, and creates new ones when it is switched on. Tutorial code missing imports slipped in as well.
> Navigation code functional again

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ChannelTableModel.java
When setting the channel exposure for a channel that is not listed in the
MDA window, the code would previously set the exposure for that channel
back to the default.  This change ensures that the AcqEngine will not
touch the exposures of channels it has no knowledge about.
In general, the channel exposure code is still complicated, and the
GUI code goes through the same function many times.  This may be another
example of the complexity of the GUI code and the use of multple similar
mechanisms for the same purpose.  Complete refactoring is desirable, but
currently out of the scope of the achievable.
> Studio: Fixes bug in remembering Channel Exposures.

- mmstudio/src/main/java/org/micromanager/data/Coords.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultCoords.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
Occassionally, the Precheck Condition at: org.micromanager.display.internal.event.DataViewerMousePixelInfoChangedEvent.<init>(DataViewerMousePixelInfoChangedEvent.java:96) fails.  It is unclear why, or how to reproduce that situation, but I suspect that it leads to crashes when users leave the mouse in the display window during long acquisitions.  This change no longer produces the complete stacktrace in the output, but instead logs the offending Coords (which is more useful information at this point). Hopefully this will also avoid crashes, and can help to pinpoint the underlying bug that cause this problem.
In addition some Javadoc was added to Coords, and an unnecessary copy in DefaultsCoords was removed.
> Studio: Attempt to deal with MouseDisplayInfo bug.

- mmstudio/src/main/java/org/micromanager/display/DisplayWindow.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
- plugins/ChannelCorrector/src/main/java/org/micromanager/channelcorrector/ChannelCorrectorFrame.java
Studio: DisplayWindow no longer shows itself. This lead to subtle bugs that were anticipated by the previous author.  A displaywindow showing itself during creation would create a number of events that other behavior relies on.  However, since other code can only register for events after creation, these events were missed.  The previous work-around was to put the code showing the Window in an EDT-InvokeLater call, with the explicit hope that other code would register itself before the window was actually shown.  Of course, this wouldwork sometimes, and not other times. This PR no longer shows the DisplayWindow during creation.  Instread, there is an API call show() that needs to be called by the calling code after registering for events.
> Showing a DisplayWindow uncoupled from its creation

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- plugins/ZProjector/src/main/java/org/micromanager/zprojector/ZProjectorPluginExecutor.java
MDA Summary now takes multiple positions into calculation of nr. of images and Dataset size.
ZProjector now uses metadata of the first image in the projection rather than a random image in the input dataset.
> Fixes MDA Summary and ZProjector metadata

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
This PR applies a treatment similar to 9ee975aaeadbccd2924152faf8f6d90617bed880 for when MMStudio is started using a `profileNameAutoStart` startup argument.
Previously user profiles that wanted to use the "Day" skin would cause the UI to load improperly when the startup argument was used, now it works as expected.
> When MMstudio is started with a profile name startup argument, make sure to apply the correct skin for the profile.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/utils/FileDialogs.java
- mmstudio/src/main/java/org/micromanager/quickaccess/internal/controls/SavedMDAButton.java
FileDialog would write the last used path to preferences, but not update the path in the current FileType.  Now it will.
Acquisition settings moves its FileType to the FileDialogs class (where other FileTypes are also hosted).
> Studio: FileDialog now stores last path as expected

- plugins/ChannelCorrector/src/main/java/org/micromanager/channelcorrector/ChannelCorrectorFrame.java
- plugins/ChannelCorrector/src/main/java/org/micromanager/channelcorrector/utils/ImageAffineTransform.java
as Bicubic leads to weird grey scale distributions.
May need to switch to using BoofCV.
> ChannelCorrector: Switch to nearest neighbor interpolation,

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
This PR implements something that was suggested in a `TODO` comment. Rather that giving each DisplayController a unique ID with a lengthy hash code, we now use a counter to make sure that each object has a unique number during runtime. The end result is that display window titles and other places that refer to the display controller will be more human readable.
For example when you snap an image you will see "Preview-1 (100%)" rather than "Preview-86839238756021256 (100%)"
> Sequentially number displays rather than using the hashcode

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
writer when appropriate.  Should result in ImageJ opening certain
datasets correctly again.  Fixes regression reported in issue #894
> Studio: Restore adding order=zct ImageJ tag in MTiff

- buildscripts/ivy.xml
- exception when inspecting jar classpaths on windows
- bug in translating calls to java
> Pycro-manager-java to 0.8.9 to fix two small bugs

- MMCoreJ_wrap/MMCoreJ.i
The current version of MMCoreJ extends the autogenerated code for `StrVector`, `BoolVector`, and `UnsignedVector` so that they implement the `Iterable` interface.  This makes it much simpler to work with these classes in Java.
This PR simply applies the same treatment to `LongVector`, `DoubleVector`, and `CharVector`.
If this looks acceptable I have one question before merging. The autogenerated `get()` method of `LongVector` returns `int` rather than `long`. This means that we have to cast from `int` to `long` in order to act as an `Iterable<Long>`, is this ok or should `LongVector` actually implement `Iterable<Integer>`?
> add iterator interface for more MMCoreJ "vectors"

- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
It leads to strange unexpected behavior, and the intent is not clear either.
This may need to be revisited.
> Studio: No longer inject remembered channel display Settings.

- mmstudio/src/main/java/org/micromanager/data/internal/PropertyKey.java
coming from camera device adapters.
The "Binning" property was meant to provide numbers, i.e. 1, 2, 4, etc.. Hamamatsu provided 1x1, 2x2, and we ended up parsing that string in the Java layer.  While testing the Spinnaker device adapter, I discoveerd that the Binning property provided the value "Mode0", which of course leads to Exceptions.  This PR works around this by testing for sane values, and if they are insane to set binning to 1.  Of course, it is desirable to fix this at the root (i.e. in the device adapter), so maybe this change is not desired.  Most importantly, there should be some kind of mechanism to make it impossible to write a device adapter that delivers anything but a number.  Maybe there should be a SetBinning() and GetBinning function in the api, and we should no …
> Studio: Handle more strange forms of binning property

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
The main issue is that there are  two authorities for he channelgroup
is and these went out of sync on failure to set the channelgroup.  This change
fixes one place that they could go out of sync, but there could be
more such places.  Two sources of the same information are
never a great idea, but refactoring that is a bit beyond scope.
There is a related issue with setting the channelGroup in the core.
Closes issue #937
> Studio: Deal better with non-existent channelgroups.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
Closing #939 
The UI and the Acquisition Sequence Settings are now only updated in
a callback, that is started in the core when the channel group changes.
> Studio: Changing core channel group now changes MDA Dialog Correctly.  

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/utils/DaytimeNighttime.java
Dear @nicost @marktsuchida,
I found that invokeLater() causes a problem when JavaFX main application closes MMStudio frame.
Supposedly, there was a GUI synchronization calling invoked after MMCore was disposed.
Could you please remove this if you guys think it is fine with other references?
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  mmcorej.MMCoreJJNI.CMMCore_getChannelGroup(JLmmcorej/CMMCore;)Ljava/lang/String;+0
j  mmcorej.CMMCore.getChannelGroup()Ljava/lang/String;+5
j  org.micromanager.acquisition.internal.AcquisitionWrapperEngine.setChannelGroup(Ljava/lang/String;)Z+4
j  org.micromanager.internal.dialogs.AcqControlDlg.lambda$createChannelsPanel$16(Ljava/awt/event/ActionEvent;)V+16
j  org.micromanager.internal.dialogs.AcqControlDlg$$Lambda$797.actionPerformed …
```
> Check EDT for calling updateGUIFromSequenceSettings() to support multi-thread contexts

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
Not doing so caused confusing behavior when exposure times were edited
while a cell editor in the MDA dialog channel section was active. Was reported 
by Matt Pearson.
> Studio: MDA Dialog, close cell editors when user leaves window.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/DefaultAcquisitionManager.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
Bug reported by Kwasi on imagesc forum.  The script:
```
settings = mm.acquisitions().getAcquisitionSettings()
z =settings.slices()
```
would not provide the slices as defined in the MDA dialog.  This PR forces the acquisition wrapper engine (which provides the sequence settings) to calculate the slices whenever sequence settings in the engine are set.
> Fix bug not providing slices with MDA acquisition settings

- DeviceAdapters/Andor/Andor.cpp
- DeviceAdapters/Andor/Andor.h
…cquisition mode Run till abort. This is necessary for users that want to acquire large image sets. New device property Force Run Till Abort On | Off
git-svn-id: https://valelab.ucsf.edu/svn/micromanager2/trunk@17378 d0ab736e-dc22-4aeb-8dc9-08def0aa14fd
> svnMerge: update to Andor device adapter

- mmstudio/src/main/java/org/micromanager/display/inspector/internal/VerticalMultiSplitPane.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/ChannelIntensityController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
Turns out, that the UI code would always set this field and set it to 0.0 (which is a bit weird).  This PR makes it possible to omit the field alltogether (at least, as far as I have tested things), and still provide a meaningful display.
> Fixes issues in display when image metadata does not contain pixel size info

- mmstudio/src/main/java/org/micromanager/internal/pixelcalibrator/PixelCalibratorDialog.java
The PixelCalibratorDialog takes the affine transform from the calibrator, and sets the translation component to zero.  To do so, the transform is converted in an array of doubles, two values in the array are zeroed, and the array is converted back into an AffineTransform.  However, the translation components have index 4 and 5, not 2 and 5 (see definitions and code in AffineTransform.java), hence ShearX and TranslationY were zeroed rather than TranslationX and TranslationY. 
Fixed now.
> Studio: Fix bug in removing translation component of affine transform.

- mmstudio/src/main/java/MMStudioPlugin.java
Closes GH-1010.
Just a comment instead of moving the class to an `internal` package, because it's probably not worth the amount of testing that would be needed, given that the launch mechanism will change as we migrate to the ImageJ2 launcher.
> Add comment re MMStudioPlugin not being API

- mmstudio/src/main/java/org/micromanager/data/Storage.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageSinglePlaneTiffSeries.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
All imlementations had int as the underlying type, so null could never
have been returned. Closes #1013
> Studio: Storage.geMaxIndex() now return int rather than Integer, Closes #1013.

- mmstudio/src/main/java/org/micromanager/display/inspector/AbstractInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/InspectorController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/InspectorSectionController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/comments/CommentsInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/overlays/OverlaysInspectorPanelController.java
This PR makes the following changes:
1: Previously all UI content of the `Inspector` panel would be removed and completely reconstructed each time the `Inspector` was  attached to a new `DataViewer`. This led to some confusing behavior where code in the `detachDataViewer` method of `AbstractInspectorPanelController` implementations would be ineffective since a completely new instance of every `InspectorPanelController` was being created for every new attachment event. Now each `InspectorPanelController` is only constructed once during the construction of a new `Inspector` panel. The only notable difference to a user is that the `Inspector` panel will now show a section for every available `InspectorPanelController` even if  `InspectorPanelPlugin.isApplicableToDataViewer` returns `false`. …
> Improve inspector panel and overlay settings.

- mmstudio/src/main/java/org/micromanager/PositionListManager.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultPositionListManager.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/PositionListManager.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/MMPositionListDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionListDlg.java
- plugins/ASIdiSPIM/src/main/java/org/micromanager/asidispim/api/ASIdiSPIMImplementation.java
Also deprecates the function markCurrentPosition, as it does not seem to belong with PositionListManager.  This should be probably be implemented in a future StageManager.
> Position list manager Refactoring.  Pull the PositionListManager implementation out of MMStudio

- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
This changes moves the callback signaling the new state of the shutter out of the lock.  I can not think of a reason that it should be inside the lock, and there are documented cases (https://forum.image.sc/t/occasional-crashes-when-starting-acquisition/46305/2) where this causes a deadlock involving the AWT.
> Studio: Avoid deadlock that occurs in rare circustances.

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
Working with the "Device Property Browser" can be extremely slow for configurations with many properties. In my case I am seeing delays of ~6 seconds.  This is because after each adjustment of a property, the `MMStudio.updateGUI()` method is called with `fromCache` set to `false`, meaning that the value of every property must be requested from the hardware.
Upon inspection of debug log files it can be seen that many properties are requested twice or in some cases three times. This is because the property values are requested once from a call to `core_.updateSystemStateCache()` and may then be requested again from a call to `pad.refreshStructure(fromCache)` and then again with a call to `propertyBrowser_.refresh(fromCache)`
This pull request changes the implementation of `updateGUI` so …
> Make  `MMStudio.updateGUI` more efficient

- autofocus/src/main/java/org/micromanager/autofocus/Autofocus.java
- autofocus/src/main/java/org/micromanager/autofocus/AutofocusDuo.java
- autofocus/src/main/java/org/micromanager/autofocus/AutofocusTB.java
- autofocus/src/main/java/org/micromanager/autofocus/HardwareFocusExtender.java
- autofocus/src/main/java/org/micromanager/autofocus/OughtaFocus.java
- mmstudio/src/main/java/org/micromanager/AutofocusManager.java
- mmstudio/src/main/java/org/micromanager/AutofocusPlugin.java
- mmstudio/src/main/java/org/micromanager/events/AutofocusPluginShouldInitializeEvent.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/utils/AutofocusBase.java
- mmstudio/src/main/java/org/micromanager/internal/utils/CoreAutofocus.java
- mmstudio/src/main/java/org/micromanager/internal/utils/DefaultAutofocusManager.java
Adds a function initialize to AutofocusPlugin and AutofocusBase.
Adds a function initialize to the AutofocusManager, which calls the
initialize function in all known autofocusplugins.
MMstudio now calls that initialize function rather than creating
the event.
Also removed public modifier from interfaces that I touched since
those modifiers are not needed.
> Studio-Autofocus: Removed use of AutofocusShouldInitializeEvent. Closes #1011

- mmstudio/src/main/java/org/micromanager/acquisition/internal/DefaultAcquisitionManager.java
- mmstudio/src/main/java/org/micromanager/internal/MMCache.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/OptionsDlg.java
- mmstudio/src/main/java/org/micromanager/internal/menus/ToolsMenu.java
This PR introduces two new classes which take over functionality that was previously performed directly by MMStudio. There should be no changes to the functionality of Micro-Manager, the goal of this PR is just to make MMStudio more organized and readable.
`MMCache` is essentially just a rename of the `StaticInfo` class and replaces these public methods of `MMStudio`:
```updateXYPos
updateXYPosRelative
updateZPos
updateZPosRelative
updateXYStagePosition
getCachedXPosition
getCachedYPosition
getCachedZPosition
getCachedBitDepth
getCachedPixelSizeUm
getCachedPixelSizeAffine
```
The `MMSettings` class is currently an internal class of `MMStudio` and is responsible for setting and retrieving top-level application preferences and replaces these public methods of `MMStudio`:
``` …
```
> Delegate functionality from MMStudio to helper classes.

- acqEngine/src/main/clj/org/micromanager/acq_engine.clj
After PR #1061 the acquisition engine stopped working since one of the public method of MMStudio that it had been using was no longer present. This PR fixes the clojure code to make the correct call to the equivalent API method.
> Fix Call to non-api method of MMStudio in Clojure Acquisition Engine

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/PropertyEditor.java
This PR contains 3 independent changes that all have to do with avoiding duplicate calls certain functions. Each of the 3 changes are contained in their own commit so it is easy to view each one separately.
1: The `MMStudio.onPropertiesChanged` event handler initiates a refresh of the GUI which involved updating the property cache. However, `CoreEventCallback.onPropertiesChanged` already updates the property cache, there is no reason to do it twice.
2: The `PropertyEditor.onPropertiesChanged` event handler calls `PropertyEditor.refresh` . However,  `MMStudio.onPropertiesChanged` also indirectly calls `PropertyEditor.refresh` through a call to `refreshGUI`. There is no reason to refresh the Property Editor twice.
3: `PropertyEditor.setValueAt` calls `PropertyEditor.refresh` and then …
> Reduce redundant function calls.

- mmstudio/src/main/java/org/micromanager/internal/MMROIManager.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
This PR seeks to more closely align the  `MMStudio` class with the "Single-responsibility principle" by moving public methods used by the `MainFrame` ROI buttons from `MMStudio` to a new class which can be accessed through the new `MMStudio.roiManager()` method.
This PR also makes some formatting changes to the `MMStudio` constructor to make it a bit easier to read by condensing into fewer lines. (I think an 80 character line-length limit is pretty dated at this point)
> Move ROI functionality from MMStudio to a dedicated ROI manager

- mmstudio/src/main/java/org/micromanager/profile/internal/UserProfileAdmin.java
If that fails too, it creates a new profile.  Avoids previous uncaught exception causing MM failing to start upon borked profile. Underlying cause: creation of borked profile is unclear, but will be hard to figure out.
Closes #1084
> Studio: Catches profile read exception and attempts to read backup profile.

- DeviceAdapters/Omicron/OmicronDeviceDriver.cpp
Closes #957 
git-svn-id: https://valelab.ucsf.edu/svn/micromanager2/trunk@17422 d0ab736e-dc22-4aeb-8dc9-08def0aa14fd
> Omicron: prevent access violation on shutdown by not calling ExXShutdownDLL()

- autofocus/src/main/java/org/micromanager/autofocus/OughtaFocus.java
- libraries/ImageProcessing/src/main/java/org/micromanager/imageprocessing/FHT_NoScaling.java
- libraries/ImageProcessing/src/main/java/org/micromanager/imageprocessing/ImgSharpnessAnalysis.java
- plugins/SharpnessInspector/build.xml
- plugins/SharpnessInspector/src/main/java/org/micromanager/sharpnessinspector/SharpnessEvaluator.java
- plugins/SharpnessInspector/src/main/java/org/micromanager/sharpnessinspector/SharpnessInspectorController.java
- plugins/SharpnessInspector/src/main/java/org/micromanager/sharpnessinspector/SharpnessInspectorPlugin.java
- plugins/SharpnessInspector/src/main/java/org/micromanager/sharpnessinspector/ui/JFreeTextOverlay.java
- plugins/SharpnessInspector/src/main/java/org/micromanager/sharpnessinspector/ui/SharpnessInspectorPanel.java
This PR adds an inspector plugin called "Image Sharpness" which provides a real-time plot of image sharpness within an ROI. The x axis can be set to `Time` or to `Z` in which case the current Z position of the default Z stage is used. This only works well if the ZStage provides consistent updates of it's position.
In addition to real-time analysis of the image you can use the `Scan` button to sweep through a range of Z positions and plot the sharpness as a function of Z.
The methods of evaluating sharpness are the same as those used by the OughtaFocus Plugin. In order to facilitate this, the sharpness analysis code previously found in `org.micromanager.autofocus.internal.oughtafocus` is now in the libraries folder and ends up in `org.micromanager.imageprocessing`.
Known issue: The axis …
> Sharpness Inspector Plugin

- mmstudio/src/main/java/org/micromanager/internal/DefaultApplication.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultPositionListManager.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/MMPositionListDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionListDlg.java
- mmstudio/src/main/java/org/micromanager/internal/positionlist/PositionTableModel.java
This PR:
- Fixes an issue where an update to the position list of the singleton `MMPositionListDlg` would result in updating the position list of all instances of `PositionListDlg`
- Fixes an issue where updates to the position list of an instance of `PositionListDlg` would not be reflected in the UI until the user pressed the `Refresh` button.
- Removes some unused references to Studio and some unused imports.
> Fix Issue with MMPositionListDlg - PositionListDlg distinction

- mmstudio/src/main/java/org/micromanager/PositionList.java
Tested with the following script:
```
import org.micromanager.PositionList;
fileLocation = "C://tmp//poslist";
PositionList posList = mm.positions().getPositionList();
for(pos : posList){
pos.setProperty("test", pos.getLabel());
}
posList.save (fileLocation);
posList2 = new PositionList();
posList2.load(fileLocation);
for(pos : posList2){
String[] names = pos.getPropertyNames();
for (String name : names){
mm.scripter().message(name+": "+pos.getProperty(name));
}
}
```
Closes #1160
> Studio: Now restores properties that were stored with property list

- .gitmodules
This branch will be set via github action to always stay up to date with the `master` branch. This branch is used to easily check out all code, including private repositories.
After checking out this branch all submodules should be available:
To make sure they are all initialized: `git submodule update --init --recursive`
To make sure all submodules are updated to their most recent commit on their default branch: `git submodule update --remote --recursive`
> change default branch of mmCoreAndDevice submodule to privateMain

- .github/workflows/updatePrivateMain.yml
Adds a check for the repository name so that the action will only run on the main repository.
> Prevent forked repositories from trying to run github actions.

- configure.ac
- m4/ax_boost_filesystem.m4
The ```ax_boost_filesystem.m4``` has been originally downloaded from https://www.gnu.org/software/autoconf-archive/ax_boost_filesystem.html.
Similar patch has been applied to ```mmCoreAndDevices``` submodule yet where the effect is limited to public device adapters.
Changes in this patch allow integration of Boost.Filesystem in ```MMCore*```.
@nicost Could please move these changes also to SVN?
Precisely:
- copy ```ax_boost_filesystem.m4``` to ```<root>/m4/```
- add ```AX_BOOST_FILESYSTEM``` to:
- ```<root>/configure.ac```
- ```<root>/DeviceAdapters/configure.ac```
> Fixed integration of Boost.Filesystem.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/DefaultAcquisitionManager.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
Adds a function AcqDialog.updateGUIBlocking, that is now called by acquisitionManager.setAcquisitionSettings().  This assures that the acquisition settings are actually set when this function returns.  Previously, rare bugs where see when running a script with the sequence:
```
mm.acquisitions().set_acquisition_settings(ssb.build())
mm.acquisitions().run_acquisition_nonblocking()
```
I expect this update (only to the implementation of the API function acquisitions().setAcquisitionSettings()) to fix this problem.
> AcqDialog implementation fixes

- mmstudio/src/main/java/org/micromanager/Application.java
- mmstudio/src/main/java/org/micromanager/ApplicationSkin.java
- mmstudio/src/main/java/org/micromanager/PropertyManager.java
- mmstudio/src/main/java/org/micromanager/PropertyMap.java
- mmstudio/src/main/java/org/micromanager/PropertyMaps.java
- mmstudio/src/main/java/org/micromanager/Studio.java
- mmstudio/src/main/java/org/micromanager/UserProfile.java
- mmstudio/src/main/java/org/micromanager/acquisition/AcquisitionManager.java
- mmstudio/src/main/java/org/micromanager/acquisition/SequenceSettings.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/DefaultAcquisitionManager.java
- mmstudio/src/main/java/org/micromanager/alerts/Alert.java
- mmstudio/src/main/java/org/micromanager/alerts/AlertManager.java
- mmstudio/src/main/java/org/micromanager/alerts/UpdatableAlert.java
- mmstudio/src/main/java/org/micromanager/data/DataManager.java
- mmstudio/src/main/java/org/micromanager/data/Datastore.java
- mmstudio/src/main/java/org/micromanager/data/RewritableDatastore.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataManager.java
- mmstudio/src/main/java/org/micromanager/display/ChannelDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultPropertyManager.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- plugins/ASIdiSPIM/src/main/java/org/micromanager/asidispim/AcquisitionPanel.java
- plugins/ASIdiSPIM/src/main/java/org/micromanager/asidispim/utils/AutofocusUtils.java
- plugins/ImageFlipper/src/main/java/org/micromanager/imageflipper/FlipperConfigurator.java
- plugins/PTCTools/src/main/java/org/micromanager/ptctools/PtcToolsExecutor.java
Closes #1019
Only thing missing is access function for PropertyMaps.Builder().  I am not sure where that function should be.  The only logical place is the Studio interface itself. Suggestions?
PropertyMaps is a bit chaotic with the Builder extending a deprecated interface. Would be nice to clean this all up after the release.
> Make all Builders uniform

- buildscripts/ivysettings.xml
Removes an unused reference resolver from Ivy settings that results in the `ant -f fetchdeps.xml` command reporting many errors.
> remove unused reference resolver from IVy

- mmstudio/src/main/java/org/micromanager/internal/dialogs/IntroDlg.java
The introduction dialog currently acts as an ownerless JDialog. In some cases where there are many windows open the intro dialog will end up behind a bunch of other windows and since it doesn't have it's own entry on the Windows taskbar it can be a pain to bring it to the front.
This PR simple calls the JDialog constructor with a `null` owner in order to more properly implement an ownerless dialog. See the constructor documentation for more information: https://docs.oracle.com/javase/7/docs/api/javax/swing/JDialog.html
It also sets the Micro-Manager icon as the dialog's icon in the task bar.
> Give IntroDlg it's own taskbar entry

- mmstudio/src/main/java/org/micromanager/data/Datastore.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDatastore.java
Resolves #1016. As best as I can tell, there is no existing code that tries to add images before adding metadata.
> Forbid setting summary metadata after adding images to datastore

- .github/linters/readme.md
- .github/linters/sun_checks.xml
- .github/workflows/lint.yml
- .github/workflows/updatePrivateMain.yml
This PR adds a Github workflow that will lint any new code in a Pull Request or that is directly pushed to a branch other than `master`
The workflow can also be triggered manually from the `Actions` tab. In this case the full repository will be checked rather than just the newly changed code.
The code style rules are defined in `.github/linters/sun_checks.xml` which is identical to the Google Java style guide except that the indentation rules have been swapped from multiples of 2 to multiples of 3.
In the future I might make sense to add an intellij project to source control which is preconfigured with the correct module structure and coding style.
See here for an example of the linting output when run manually on the full codebase: …
> Add automatic linting of pull requests

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDatastore.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/metadata/PlaneMetadataInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYNavigator.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/ZNavigator.java
- mmstudio/src/main/java/org/micromanager/internal/utils/PrioritizedEventBus.java
- mmstudio/src/main/java/org/micromanager/internal/utils/ProgressBar.java
This PR names all threads running in threadpools.  Naming showed that the ThreadPools produced by the PrioritizedEventBus were not removed.  This PR shuts down that ThreadPool when it is not longer needed.
In addition, several deadlocks were observed that could be avoided by executing display related code on the EDT.
> No longer keeps thousands of threads running.  Fix several deadlocks in EDT

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/AxisLinker.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
Noticed that on short runs many UI elements remain, but these get cleaned up on longer runs.  With DisplayController being released, it is likely that most of its descendants (except the sneaky ones that create backdoor references from plugin to DisplayController) can be left alone.  I will go back in and bring back final objects (and no longer set them to null) wherever possible.  Need this build today though;)
> Studio: DisplayController object is now GCd.

- buildscripts/codestyle/readme.md
- buildscripts/codestyle/sun_checks.xml
The checkstyle rules are loosened in the following ways:
- Member variable names are permitted to end with an underscore
- Parameter names, member names, and many other name types are allowed to have only a single lowercase letter at the beginning, i.e. `xLabel`
- All-caps abbreviations are allowed. For example, `refreshGUI` is fine and doesn't need to be changed to `refreshGui`
> relax naming checks

- libraries/Projector/src/main/java/org/micromanager/projector/internal/ProjectorControlForm.java
These alerts caused massive problems when issues
too many times.  That by itself is a problem for another day, but something good to remember.
> Projector: log writer no longer issues alerts when log directory is empty.  

- plugins/SharpnessInspector/src/main/java/org/micromanager/sharpnessinspector/SharpnessInspectorController.java
Closes #1229.  The plugin had everything build-in to do this correctly, but the flag signaling whether or not to evaluate images was initialized to the wrong value.
> SharpnessPlugin: Do not evaluate images until opened.

- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
- mmstudio/src/main/java/org/micromanager/display/internal/animate/AnimationController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
When acquiring 50,000 images at 5 msec exposures, the display would start off nice and fast, but slow down over time.  This PR addresses that slowness, at least for single channel data.  Most of the gains seem to be made by optimizing the Storage function "getImagesIgnoringAxes".  This function would iterate through all Coords in the dataset, remove the requested axes and check for identity.  This becomes slow with large collections.  By keeping track of the axes in the dataset, and only doing the complete check when the "missing axes" are actually present in the dataset, this bottleneck was removed.  However, this approach does not work when the "missing axes" are present in the dataset (such as in multi-camera datasets), so it will be good to think about alternative optimizations (none …
> Adrresses slowness of display of  datasets > ~10,000 images

- mmstudio/src/main/java/org/micromanager/display/DisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/DisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
To enable setting (and deleting and replacing) all channelDisplaySettings at once.
Failed to replicate the strange bug that I had seen before of multi-camera display appearing with a single camera config file, so did not put the new function in action yet.
Also lots of CheckStyle cleanup, but that should all be inconsequential, other than that the code looks prettier and the Javadoc improved.
Closes #1247.
> Display settings API change, add function to DisplaySettings.Builder

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- Prevents a deadlock that could occur when closing a display that is animating.
- Prevents situations where the display has incorrect axes, by updating the axes when the display freezes.
- Fixes a bug where closing one display would effectively kill the linkmanager, making it impossible to link the remaining displays.
Also applied Checkstyle recommendations to DisplayController.
> Fixes a few issues with the Display

- mmstudio/src/main/java/org/micromanager/display/internal/animate/AnimationController.java
closing live window.  Shutting down the animation controller from the
EDT should not lead to deadlock, which it used to when the animation was
running.  I do not see a reason for shutdown to be synchronized, as all the
functions it calls are synchronized.  Possibly setting perfMon_ to null should
be behind a lock.
Closes #1261
> Studio: Avoid deadlock in animationcontroller when

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/data/Annotation.java
- mmstudio/src/main/java/org/micromanager/data/internal/CommentsHelper.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultAnnotation.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataSaver.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDatastore.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageSinglePlaneTiffSeries.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffWriter.java
Both Single and MultiPageTiff storage now stores Summary and Per Image comments in a file "comments.txt" in the acquisition directory.  Even after opening a file, changes to the comments will be stored in that file.  One possible addition would be to preserve the original comments, but it is already a big step forwards that things actually work.  The code is not easy to understand, and probably could use some structural improvements, but that will happen another time.
> Makes Annotations work how they presumably were meant to work.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/CenterAndDragListener.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/UiMovesStageManager.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYNavigator.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYZKeyListener.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/ZNavigator.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/ZWheelListener.java
Closes #1278.
- Adds option to snap an image after moving.
- Now moves stage to move the sample as expected based on the image, rather than based on the stage coordinates.
- Lots of checkstyling the internal navigation code.
> StageControl plugin new features

- bindist/any-platform/MMConfig_demo.cfg
This adds an example to the demo config to make this more discoverable. This also helps when using the demo config to develop a GUI application. 
This is particularly important for people working with pymmcore(-plus), as when doing so you can end up working with config files not generated directly by micromanager. 
See also https://forum.image.sc/t/how-to-set-channelgroup-in-config-file/55746
> Add ChannelGroup setting to demo config

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/FileSet.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/InvalidIndexMapException.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
When a script would request to splitfiles by position, but did not provide a name for each position in the image metadata, all data would go to the exact same file, in effect over-writing each position with the next.  This PR adds a check for the "Default" position name, and autonumbers positions when found.
> Multi page tiff, avoid overwriting same file in certain conditions

- mmstudio/src/main/java/org/micromanager/internal/utils/WindowPositioning.java
It prevented window positions to be remembered correctly in multi-screen
scenarios.
Closes #1296
> Studio: Fix bug in function fitWindowInScreen.

- doc/how-to-build.md
note to compile partial device adapters and in newer gcc, tested on gcc-11, openSUSE Tumbleweed 20210802.
> note to compile partial device adapters and in newer gcc

- autofocus/src/main/java/org/micromanager/autofocus/OughtaFocus.java
Avoid a non-standard exception class which loses the error message.
Should preserve information in cases like #1299.
> Preserve exception in OughtaFocus

- mmstudio/src/main/java/org/micromanager/data/Image.java
- mmstudio/src/main/java/org/micromanager/data/internal/BufferTools.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultImage.java
This PR adds a method to `Image` that returns a `byte[]` array of the raw pixel data regardless of the pixel data type.
I use this method to efficiently transfer image data to Python using Py4J. More information [here](https://www.py4j.org/advanced_topics.html#byte-array-byte). A similar approach may be useful to Pycro-Manager if not already implemented.
This method could also be useful for other low-level processing of raw data.
The primary implementation is added to `BufferTools` which `DefaultImage` then calls upon.
> Add `getByteArray` to `Image`

- plugins/CRISP/src/main/java/com/asiimaging/crisp/CRISPFrame.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/CRISPPlugin.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/UserSettings.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/data/Defaults.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/data/Icons.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/data/Ranges.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/CRISP.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/CRISPSettings.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/CRISPTimer.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/ControllerType.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/PropName.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/PropValue.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/ButtonPanel.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/PlotPanel.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/SpinnerPanel.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/StatusPanel.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/plot/FocusData.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/plot/FocusDataSet.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/plot/PlotFrame.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/utils/DialogUtils.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/utils/FileUtils.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/utils/WindowUtils.java
- plugins/CRISP/src/main/java/com/asiimaging/ui/Button.java
- plugins/CRISP/src/main/java/com/asiimaging/ui/CheckBox.java
- plugins/CRISP/src/main/java/com/asiimaging/ui/ComboBox.java
- plugins/CRISP/src/main/java/com/asiimaging/ui/Method.java
- plugins/CRISP/src/main/java/com/asiimaging/ui/Panel.java
- plugins/CRISP/src/main/java/com/asiimaging/ui/Spinner.java
Nothing major, just changing license comment type from javadoc to block comment.
> Crisp plugin: fixed license comment type

- plugins/CRISP/src/main/java/com/asiimaging/crisp/CRISPPlugin.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/CRISPTimer.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/PlotPanel.java
Fixed a bug with the focus curve plot button not being re-enabled after plotting. Fixed the CRISP timer during logCal, if you clicked on log cal when polling was off it would set the skip counter and count down as soon as you enabled polling again in any state.
> CRISP: fixed plot button and timer skip counter

- plugins/CRISP/src/main/java/com/asiimaging/crisp/data/Ranges.java
When fixing the device adapters I realized this value needs to be higher.
> CRISP: increase GainMultiplier spinner max value

- mmstudio/src/main/java/org/micromanager/events/internal/DefaultChannelExposureEvent.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultApplication.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
When the device adapter calls OnPropertiesChanged in the setExposure method
(such as done by the PVCAM adapter), the exposure time would reset to the
previously known exposure time for the channel and group (when synchronization
with the MDA was requested).  This was caused by the setExposure function not
updating the value stored by AcqDialog.  It so turns out that the DefaultChannelExposureEvent
was not inheriting from ChannelExposureEvent, hence the event was never processed
(this is one of those instances where I do not like the opaque structure of
the agave-google bus).  Fixing this, and making sure the event is posted
before actually setting the exposure time in the core (which can result in
the OnPropertiesChanged callback) solves the issue hopefully for good.
Closes #1319
> Studio: fix inability to set exposure time in certain conditions.

- mmstudio/src/main/java/org/micromanager/IntroPlugin.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/ImageJBridge.java
Best to escape non-ascii characters, even though our source is
understood to be UTF8. See #945.
> Remove mu/micro symbol from Java source

- plugins/CRISP/src/main/java/com/asiimaging/crisp/CRISPPlugin.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/device/CRISP.java
This will make sure that the "update rate ms" spinner is usable on CRISP firmware version 3.38.
> CRISP: make sure to set firmware version and letter

- mmstudio/src/main/java/org/micromanager/internal/navigation/XYNavigator.java
> Studio: When XY stage movement fails, show an error rather than only log.

- mmstudio/src/main/java/org/micromanager/events/internal/ChannelColorEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/CoreEventCallback.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultApplicationSkinEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultAutoShutterEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultChannelExposureEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultChannelGroupChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultConfigGroupChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultEventManager.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultExposureChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultGUIRefreshEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultLiveModeEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultNewPositionListEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultPixelSizeAffineChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultPixelSizeChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultPropertiesChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultPropertyChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultSLMExposureChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultShutdownCommencingEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultShutterEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultStagePositionChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultStartupCompleteEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultSystemConfigurationLoadedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultXYStagePositionChangedEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/NewPluginEvent.java
- mmstudio/src/main/java/org/micromanager/events/internal/ShutterDevicesEvent.java
It is difficult to completely avoid loops cause by event callbacks from the core.  The Java class "CoreEventCallback" has a function "setIgnoring" that so far was only used for "OnPropertiesChanged" callbacks.  This PR uses the flag for all Core Callbacks, so when the flag is set to true, no events will be passed through to the Java layer.  This is useful, for instance when loading a configuration file.  
I expect that this will avoid the situation where MM on startup does not respond because it continues in a loop setting and unsetting the channel group.  This bug is difficult to reproduce on my system, but others seem to run into it a lot.
> Adds a flag to temporarily disable processing of core events

- buildscripts/nightly/mkportableapp_OSX/mkportableapp.py
- buildscripts/nightly/nightlybuild_macOS_defs.sh
- buildscripts/nightly/nightlybuild_macOS_deps.sh
- buildscripts/nightly/nightlybuild_macOS_mm.sh
- configure.ac
- mmstudio/Makefile.am
This adds `buildscripts/nightly/nightlybuild_macOS_*.sh`, which work with macOS 12.0 SDK.
The existing scripts (`buildscripts/nightly/nightlybuild_OSX_*.sh`) are kept unmodified (they should be removed once our CI no longer needs them).
The new scripts build only 64-bit.
> New mac build scripts for recent macOS and Xcode tools

- buildscripts/nightly/nightlybuild_macOS_defs.sh
It is better to allow the default SDK to be used, because the SDK may be
present in the Command Line Tools for Xcode, and also gets updated
frequently.
In particular, having an incorrectly set SDKROOT can cause cryptic
errors when building Boost.
> macOS build: Avoid hard-coding the SDK version

- buildscripts/nightly/nightlybuild_macOS_defs.sh
Make it work also with, e.g., temurin or an old copy of AdoptOpenJDK.
> macOS build: Avoid hard-coding JAVA_HOME

- buildscripts/ivy.xml
- buildscripts/ivysettings.xml
IT departments start to disallow software that includes log4j.  This PR removes log4j, but does not do so cleanly, because the latest scifio release still brings in a dependency on log4j.  Hitting the missing functionality is extremely unlikely, as log4j was only used by a library by Herr Saalfeld that we were not using, but that was brought in with imglib2-roi.
> Avoid shipping log4j

- mmstudio/src/main/java/org/micromanager/internal/propertymap/PropertyMapJSONSerializer.java
Previously unbeknowst to me, variable names are used in this code as
keys to interpret JSON data.  Making these variable names conform to our
conventions broke parsing of the serialized preoptymaps.  Quite ugly,
but reverting the variable names fixes this.
> Studio: Fixes bad bug preventing loading of propertyMaps.

- buildscripts/nightly/nightlybuild_macOS_defs.sh
- buildscripts/nightly/nightlybuild_macOS_deps.sh
This is only useful for testing the build, for now.
The macOS nightly build script now works correctly when run on an Apple
arm64 computer, and produces x86_64 binaries.
The only change needed was figuring out how to cross-compile Boost,
which appears to be broken when using only command-line options to b2.
(I.e., the method we used to use for Intel 32/64-bit does not work.)
The method used here may become useful if we eventually decide to build
arm64 or universal2 binaries.
Actually running Micro-Manager on arm64 machines (via Rosetta 2 or
otherwise) is not addressed (the main issues are Gatekeeper path
randomization and, if running the x86_64 version, how to launch an
x86_64 JVM).
> Make macOS x86_64 build work on Apple arm64

- buildscripts/installer_Windows.iss
This follows #1387. We don't want the DLLs installed by previous
versions hanging around, in case (in the future) JOGL is updated and a
conflict arises.
> Remove JOGL DLLs upon installation

- buildscripts/fetchdeps.xml
- buildscripts/ivysettings.xml
Remove obsolete repositories and allow to (optionally) have the script fail when there are unresolved dependencies.
> Ivy cleanup

- buildscripts/ivy.xml
Closes #1394.
With this change, all dependencies are resolved.
> Remove unused cl-kernel-bindings dependency

- .github/workflows/apidoc.yml
Apparently needed, at least occasionally, for packages to install correctly.
> Add apt-get update before apidoc builds

- .github/workflows/apidoc.yml
- buildscripts/nightly/nightlybuild_macOS_defs.sh
- configure.ac
- doc/how-to-build.md
Also, let automated macOS and apidoc builds use the new default.
Closes micro-manager/mmCoreAndDevices#152.
> Autoconf: require, and default to, C++14

- mmstudio/src/main/java/org/micromanager/internal/hcwizard/LabelsPage.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/MicroscopeModel.java
State devices with more than 10 or states become very unwieldy on the Label page of the HCW.  Moreover, many of these (often digital Output) devices really do not need labels.  I run in an issue with a 32 pin output port that needed 2^32 labels, and run out of JVM memroy.  This PR only shows state devices that have the "Label" property defined.  Therefore, not defining it ensures that the user does not need to define labels.  Also, only labels that differ from the default "State-#" will now be written to file (but note that existing "State-#" labels will not be removed from a config file).
> Hardware Configuration Wizard: Only show State devices thave have a Label property on the label page.

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/profile/internal/gui/HardwareConfigurationManager.java
Closes issue #1437.
Not sure why the HardwareConfigurationManager lives in profile-internal.
> Studio: loading a new config file now populates the shutter dropdown correctly

- mmstudio/src/main/java/org/micromanager/internal/hcwizard/Device.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/DeviceSetupDlg.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/PropertyTableModel.java
- mmstudio/src/main/java/org/micromanager/internal/utils/PropertyItem.java
- mmstudio/src/main/java/org/micromanager/internal/utils/PropertyValueCellEditor.java
It is sometimes desirable for a device to change its pre-initialization properties based on the setting of one or more pre-initialization properties.  This PR modifies the HCW so that it writes each pre-init property to the device after each change, and then reads back in all now available pre-init properties.  This may be a problem with devices that take a long time to read in such properties (I am not sure if this a problem in reality or not).  Since this code is needed by anyone configuring Micro-Manager it may need some scrutiny.  I used the demo state device in the branch HCWPropChangeDemoTest of mmCoreAndDevices to test this code.  That branch can be deleted after testing.
Closes #1442.
> HCW now updates device pre-init properties after each change

- mmstudio/src/main/java/org/micromanager/internal/utils/ReportingUtils.java
- mmstudio/src/main/java/org/micromanager/profile/internal/UserProfileAdmin.java
Previously, certain calls to ReportingUtil.showError would lead to null pointer exceptions and no display of the error to the user.  In addition, errors in ProfileAdmin were not shown to the user.  This PR should somewhat improve that situation.  I believe there was an issue related to this, but I can not locate it.
> Better error reporting in ReportingUtils and ProfileAdmin

- .github/workflows/apidoc.yml
- Restrict build on 'push' to branch 'main' only.
This prevents the apidoc build from firing twice when the pull request
is based on a branch in the official repo.
- Simplify names to reduce clutter.
> Avoid redundant builds on pull requests

- mmstudio/src/main/java/org/micromanager/internal/MMROIManager.java
Closes issue #950. This fix pertains only to the internal MMROIManager.  Instead of relying on ImageJ to get the active ImagePlus, it uses the Studio DisplayManager and a deprecated function to get the ImagePlus.  As long as we use ImageJ behind the scenes, I do not see a way not to use this deprecated function.
> Studio: can get and set ROI correctly in Composite images.

- mmstudio/src/main/java/org/micromanager/internal/pipelineinterface/PipelineTableModel.java
Previously, the user would not be informed, and the uncaught exception led to the user requested action (snap/live) not being executed.
Closes #1481
> Studio: When a plugin in a pipeline can not be created, ignore this plugin but show a message to the user.

- plugins/HCS/src/main/java/org/micromanager/hcs/CalibrationFrame.java
If it is really recommended, then why is it not the default?   We have now
tested this for many years and have not found porblems, whereas it makes
things much easier, so lets switch now.
> HCS: change calibration method default to recommended.

- mmstudio/src/main/java/org/micromanager/acquisition/SequenceSettings.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
This one trips me up every time.  I always use relative Z.  Absolute Z may be dangerous under certain conditions, so relative Z will always be safer.  This should not change anything for people who are already using absolute Z in the MDA, only the default for new users.
> Changes the default setting in MDA dialog for Z-Stack from absolute to relative

- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
- plugins/RatioImaging/src/main/java/org/micromanager/ratioimaging/RatioImaging.java
- plugins/RatioImaging/src/main/java/org/micromanager/ratioimaging/RatioImagingFactory.java
- plugins/RatioImaging/src/main/java/org/micromanager/ratioimaging/RatioImagingFrame.java
- plugins/RatioImaging/src/main/java/org/micromanager/ratioimaging/RatioImagingProcessor.java
Needed a way to specify the special channel names generated when using multiple cameras.  There is quite a bit of heuristics involved, but it seems to work.
> Ratio plugin: Added support for ratio images from multiple cameras.

- plugins/MMClearVolumePlugin/src/main/java/edu/ucsf/valelab/mmclearvolumeplugin/CVViewer.java
- plugins/MMClearVolumePlugin/src/main/java/edu/ucsf/valelab/mmclearvolumeplugin/events/CanvasDrawCompleteEvent.java
- plugins/MMClearVolumePlugin/src/main/java/edu/ucsf/valelab/mmclearvolumeplugin/recorder/RecorderUtils.java
- plugins/MMClearVolumePlugin/src/main/java/edu/ucsf/valelab/mmclearvolumeplugin/slider/RangeSlider.java
- plugins/MMClearVolumePlugin/src/main/java/edu/ucsf/valelab/mmclearvolumeplugin/slider/RangeSliderDemo.java
Initial brightness-contrast has always been confusing with the ClearVolume viewer.  Things were worse with an image with max brightness of 4096.  Now always relates max and min to the maximum value of the pixel (i.e. 255 or 65535) rather than the max intensity delivered by the camera.  That behaves a whole lot netter.  Also linted the code.
> ClearVolume brightness contrast

- build.xml
- buildscripts/Ant/unixprops.xml
- buildscripts/Ant/windowsprops.xml
- buildscripts/buildprops.xml
Let C++ components, including SWIG-generated sources, build where they normally do when built from Visual Studio, instead of forcing to `build/` outside of `mmCoreAndDevices/`.
This means that `ant jar` in `mmCoreAndDevices/MMCoreJ_wrap` should work after building `MMCoreJ_wrap` in Visual Studio.
Added Ant target `clean-cpp`. Fixed all clean targets.
Closes micro-manager/mmCoreAndDevices#255.
> Avoid moving C++ build dir in Windows Ant build

- buildscripts/nightly/nightlybuild_macOS_mm.sh
This hasn't been a problem in the Jenkins builds because there we overwrite version.txt before running this build script.
`version.txt` used to be maintained without a trailing newline, but now contains CRLF; let's make it work either way.
> macOS build: make work when version.txt has newline

- configure.ac
We don't need it any more, because MMCore no longer depends on Boost. The DeviceAdapters configure.ac still configures Boost for the device adapters that require it.
> Remove Boost from toplevel configure.ac

- doc/pre-commit.md
It turns out that the need for venv was limited to some version combinations of the tools (Git for Windows, Python?).
Remove and use global installation of `pre-commit`.
See discussion in #1551.
> Remove venv from pre-commit instructions

- acqEngine/src/main/clj/org/micromanager/acq_engine.clj
This is not an elegant fix, but all I can do with no knowledge of Clojure.  The acquisition engine knows the number of camera channels and should take those into account.  This fix ensures that the code tagging the metadata will use the correct camera-channel-name.
> AcqEngine: Fix bug with camera channel names, causing acquisitions with camera 2 to fail after running acquisition with multi-camera.

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataManager.java
This precludes certain operation on the datastore.  Ensure sure that it freezes.
> Studio: Fix bug when dataset is too large and the open virtual option was chosen, the resulting store was not frozen.

- mmstudio/src/main/java/org/micromanager/display/internal/animate/AnimationController.java
This change looks like it will prevent the deadlock in #1557.  I do not quite like pulling in a google class (AtomicDouble), but it seems the cleanest.  Otherwise, we should lock just the get and set fps (i.e. not synchronize them with everything else in this class.
> Studio: Prevent deadlock related to animation fps values.

- buildscripts/codestyle/idea-java-code-style.xml
- doc/pre-commit.md
I think this may provide a practical short-term fix for #1509 (pending feedback), for IntelliJ IDEA only.
The file added here (`buildscripts/codestyle/idea-java-code-style.xml`) is exported from IDEA's `Settings > Editor > Code Style > Java`, after having imported code style settings from `checkstyle.xml`. Adding this because import of `checkstyle.xml` into IDEA seems to fail on macOS (#1501) (this export was created on Windows).
It can be imported by going to `Settings > Editor > Code Style > Java`, clicking the Gear next to the Scheme, and selecting `Import Scheme > IntelliJ IDEA code style XML`. (`Settings` is `Preferences` on macOS.)
You probably want to set the Scheme to "Project" (as opposed to "Default") before importing and choose to import into the current scheme when asked. That …
> Add Java code style for IntelliJ IDEA

- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
This caused StoraRAM to hold on to images that were no longer in a (rewriteable) store.  This caused bugs (or at least, unexpected behavior) in code calling `getAnyImage()`.
Closes #1559.
> Studio: Avoid bugs caused by StorageRAM keeping a reference to anyImage_.

- mmstudio/src/main/java/org/micromanager/data/internal/PropertyKey.java
This code is very difficult to understand (still, after all these years), but I do believe it relied on a side effect.  When the Core no longer inserts the system state cache in tagged image metadata, this code throws a null pointer exception. Keep it in place just in case, but prevent null pointer exceptions.
> Studio: Prevent null pointer exception in SCOPE_DATA_KEYS metadata handling. 

- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
The code had a 100ms wait time to accomodate ASI stages going setting BUsy to false, but then moving again.  A similar problem occurs with Nikon Stages, but they need a longer wait.  We are paving over problems in the device adapters, but at least this gives an easy way for the user to make these nice cabilities usable, wheras it may be very difficult to fix this in the device adapters.  It is interesing, however, that these types of problems do not seem to show up in MDAs, so may be something else is going on.
> Studio: add way to tune extra wait for StageControl Snap after move.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/DefaultAcquisitionManager.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
This avoids the superfluous "user" metadata replicating the device state already available under the "device" metadata.
> Studio: Snap/Live now ask GetTaggedImage not to include the System State Cache in the metadata.

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffWriter.java
Calculation of the expected file size was wrong.  Classis 0 or 1 issue. Closes #1579.
> Studio: Fix bug in MpTiffWRiter resulting in many large files.

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
There still is something weird about the right side of the window, but I believe that to be a MigLayout issue rather than in our code.  Luckily, at least half the gear icon always shows.
Closes #1495
> Studio: Viewer: Ensure sliders are still shown after window resizing by operator.

- mmstudio/src/main/java/org/micromanager/display/internal/animate/AnimationController.java
This bug caused the animationController to continue repainting the canvas even after the user stopped the animation. The bug resulted from an apparent misinterpretation of the AtomicBoolean. compareAndSet function.
> Studio: Fix bug in animationController

- plugins/HCS/src/main/java/org/micromanager/hcs/ParentPlateGUI.java
- plugins/HCS/src/main/java/org/micromanager/hcs/PlatePanel.java
- plugins/HCS/src/main/java/org/micromanager/hcs/SiteGenerator.java
Previously, the plugin would sometimes use the ZStage identified in the 3 point calibration, other times the Core Focus device.  This PR ensures that the Z Stage identified in the 3 point calibration will always be used.
> HCS: ZStage now is the stage used in 3 point calibration, rather than always the core focus device.

- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/metadata/PlaneMetadataInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/internal/animate/AnimationController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/imagej/ImageJBridge.java
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorExecutor.java
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorPluginFrame.java
Previously, only ranges of axes could be selected.  That proved to be cumbersome when desiring to select a sub-set of channels.  
Also added the ability to save directly to any of the formats supported by MM.
> Duplicator plugin: select any channel, and saves output

- mmstudio/src/main/java/org/micromanager/display/ImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/CopyAsDisplayed.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/DefaultImageExporter.java
- mmstudio/src/main/java/org/micromanager/display/internal/gearmenu/ExportMovieDlg.java
- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
- mmstudio/src/main/java/org/micromanager/internal/utils/MMKeyDispatcher.java
In addition, pressing Ctrl-c in a display window will now copy the currently displayed image to the system clipboard.  This code is in MMKeydispatcher, which is no super elegant.  Suggestions for a better place are welcome, however, copying the currently displayed image with a key combination is super useful.
> Added option to copy to the system clipboard to the export images as displayed gear menu.

- autofocus/buildscripts/PFSOffsetFocusser.xml
- autofocus/src/main/java/org/micromanager/autofocus/PFSOffsetFocusser.java
Adds an autofocus plugin that sets the offset of the PFS based on software autofocus.  One would think this can be done by setting the PFS offset as the ZDrive device, but that turns out to give bad results, likely because the Z position lags behind the PFS offset drive.  See the code for further comments.  Warrants a page on the website to document.
> Pfs plus software

- mmstudio/src/main/java/org/micromanager/events/internal/CoreEventCallback.java
- mmstudio/src/main/java/org/micromanager/events/internal/DefaultConfigGroupChangedEvent.java
checks with the core cache what the current config is.  This is a cheap call, and avoids stale callbacks overwriting the actual state.
> Studio: ConfigChangedCallback: add constructor that

- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
Without this, one is confronted with a prompt to save in the top left corner without much indications which window this refers to.
> Studio: DeMinimize Window before prompting to save them.

- plugins/Magellan/src/main/java/org/micromanager/magellan/internal/magellanacq/MagellanAcqUIAndStorage.java
Reverts micro-manager/micro-manager#1734 since that code did not compile and MicroMagellan no longer worked.
> Revert "Allow explore acquisition to zoom before data"

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/data/internal/PropertyKey.java
- mmstudio/src/main/java/org/micromanager/display/DisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/ChannelIntensityController.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/panels/intensity/IntensityInspectorPanelController.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplaySettings.java
This PR was prompted by the "Ignore zero pixel" setting not being remembered (i.e. setting it, closing a window, then opening a new one would not automatically set this checkbox). It turned out that there are various (legacy?) systems to store DisplaySettings, and I surely have not completely untangled these.  However, for Snap and MDA windows, settings (including Channel Display Settings) are now stored in and retrieved from PropertyMaps, which I believe was the goal altogether.  Further clean up (including adding the ability to create a Display while specifying the desired DisplaySettings) is needed, but I believe this is a good step in the right direction until I'll have more time.
> Improvements in remembering display settings

- buildscripts/ivy.xml
- mmstudio/src/main/java/org/micromanager/internal/dialogs/IJVersionCheckDlg.java
- plugins/Deskew/src/main/java/org/micromanager/deskew/CliJDeskewProcessor.java
Also exclude unused imports caused by Clij2.  Rotate GPU deskew over its x axis, to match CPU orientation.
> Formalize dependency updates caused by Clij2

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/display/internal/event/DataViewerMousePixelInfoChangedEvent.java
event will actually take place.  Also, no longer change the channel color upon receiving a channelColorEvent.
Previously, the function displayImages would drop the request to display images if it was received before painting the images finished.  Now, this request is funneled to a ScheduledExecutor that will display the requested images 1 second later.  If other images are displayed in the mean time, the requst is cancelled.
The ChannelColorEvent previously caused the color of channels to change, when the user changed the channel color in the MDA window. That seems undesirable, so this code has been commented out and can be removed.
> Studio: display now ensures that last requested display

- mmstudio/src/main/java/org/micromanager/acquisition/internal/AcquisitionWrapperEngine.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/multimda/acqengj/MultiAcqEngJAdapter.java
constructors that were almost verbatim copies (with annoying, subtle differences).  I deprecated the form that takes JSON formatted summarymetadata, and changed all calls to the constructor to the version that takes a SummaryMetadata object as input. 
As a side effect, this fixed the problem that the channel colors set in the MDA were not 
honored in the display of an acquisition.
> Studio: Refactor MMAcquisition.  MMAcquisition contained two

- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
SummaryMetadata were incomplete.  First add MM Metadata, then convert from JSON to SummaryMetadata class.  Noticed this, because animations did not work in data acquired with AcqEngJ.
> Studio: Bug fix in AcqEngJWrapper.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/multimda/acqengj/MultiAcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultSummaryMetadata.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/OMEMetadata.java
- mmstudio/src/main/java/org/micromanager/display/inspector/internal/InspectorController.java
- mmstudio/src/main/java/org/micromanager/display/internal/imagestats/IntegerComponentStats.java
- mmstudio/src/main/java/org/micromanager/internal/pipelineinterface/PipelineFrame.java
- mmstudio/src/main/java/org/micromanager/internal/pluginmanagement/DefaultPluginManager.java
- mmstudio/src/main/java/org/micromanager/internal/pluginmanagement/PluginFinder.java
- mmstudio/src/test/java/org/micromanager/data/internal/VersionCompatTest.java
- mmstudio/src/test/java/org/micromanager/display/internal/animate/DataCoordsAnimationStateTest.java
Most remaining have to do with raw types, where I really do not know how to fix them, or the use of deprecated code (such as MDUtils), for which there is not really an alternative.  Trying to reduce the number of warnings to make it easier to spot errors (and to find potentially unintended behavior)
> Fewer warnings in mmstudio code

- buildscripts/nightly/mkportableapp_OSX/mkportableapp.py
Until now, there were no dylibs with dependencies at `@rpath`. Third-party dylibs to be installed by the user may have this. Replace with `@loader-path` so that copying the dependency dylibs into the Micro-Manager folder works.
(Preparation for addressing micro-manager/mmCoreAndDevices#368)
> Mac build: replace `@rpath` with `@loader-path`

- mmstudio/src/main/java/org/micromanager/internal/dialogs/StageControlFrame.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYNavigator.java
- mmstudio/src/main/java/org/micromanager/internal/navigation/XYZKeyListener.java
Closes #1812.  Also, change polarity of Y-buttons.  Up is now positive (as one expect it should be).  This needs some checking with an actual, calibrated camera to see if things are moving in the right direction.
> Studio-Navigation: make panel work without camera calibration.

- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorExecutor.java
Turns out the Duplicator plugin would silently crash on summary image metadata missing size information.  This PR both fixes that issue, and adds width and height info for the Snap/Live code path,
> Duplicator: now works with snap-live image data

- plugins/SnapOnMove/src/main/java/org/micromanager/plugins/snaponmove/ConfigFrame.java
- plugins/SnapOnMove/src/main/java/org/micromanager/plugins/snaponmove/MainController.java
Closes #1823.  Now remembers movement criteria between MM invocations.  Also automatically stops operation while an acquisition is running.
@marktsuchida, could you check if the way I handle pausing the monitoring thread is correct?  It works OK with the demo config.
I'd be happy to move this out of the beta menu item, probably into "Device Control".
> Snap on move improvements

- configure.ac
Following micro-manager/mmCoreAndDevices#420.
> Fix Autoconf for MMDevice/MMCore test removal

- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageSinglePlaneTiffSeries.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
Closes #1858. The implementations of the function Storage:getImagesIgnoringAxes would iterate over all known coords to check if they match or not.  This is an expensive operation, especially for large datasets.  Our code only uses this function with the axis Channels as the ignored axes, so I added code to store those in a HashMap for fast retrieval.  This change avoids the slow down in display speed for large datasets.
The function GetImagesMatching appears to be almost the same in intent.  I changed its implementations to call getImageIgnoringAxes wherever appropriate.   
There is quite a bit of redundancy in this code.  I played with creating a special class for handling Coords for all Storage implementations, but this was not very pleasant either.
> Optimizes Storage:getImagesIgnoringAxes implementations.

- mmstudio/src/main/java/org/micromanager/data/internal/ndtiff/NDTiffAdapter.java
so that it does no longer go through the complete dataset.  This may lead to problems in certain cases, but at least makes virtual datasets readable again.
Closes #1839
> Studio-NDTiffAdapter: Simplifies function getImagesMatching()

- plugins/SplitView/src/main/java/org/micromanager/splitview/SplitViewProcessor.java
Closes #1874. The Datastores now better enforce correct size information, which should be provided by the Image processors in the Summarymetadata.  So, this change fixes a regression.
> SplitView: adds new image sizes to the Summarymetadata.

- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
manifesting itself in Rewriteable RamStores (inserting same Coords many times in coordsIndexedMissingC index).
Closes #1878
> Studio: fix bug in RAMStore 

- plugins/ASIRingTIRF/src/main/java/com/asiimaging/tirf/model/TIRFControlModel.java
The plugin will now turn off fast circles mode as well as disable the scanner beam at the end of the calibration routine.
> ASIRingTIRF: update calibration routine shutdown tasks

- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageSinglePlaneTiffSeries.java
This was caused by uninitialized HashMap coordsIndexedMissingC_.  These type of errors really should be picked up by automated testing, but setting that up correctly will involve some effort.
Closes #1884
> Studio: Fixes recent bug in reading single page Tiffs.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
Not sure why this did not show up before, but skipFrames=0 (more or less the default) cause a divide by null exception.  Wondering if this also fixes #1891.
> Studio: AcqEngJ: fixed null pointer exception.

- buildscripts/ivy.xml
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/MDAAcqEventModules.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/multimda/acqengj/MultiAcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/acquisition/internal/testacquisition/TestAcqAdapter.java
Should only be merged after AcqEngJ 0.37.0 is released.  
- Repositions stages at the end of acquisition
- Actually shows error, rather than silently doing nothing.
- When using position list, moves all drives rather than only XY drives
- When using position list, updates positions after autofocus, so those are used at the next time point.
> Many improvements in AcqEngJ compat layer

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultAnnotation.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
data set, various problems arise on exit, delaying exit for hours. This PR uses a valid method to establish whether the annotations file can be written to.  It also gives up trying to write to file handles that can not be written to after 10 tries.  This gives a great performance boost. It should be evaluated if there are edge cases where this approach is detrimental.
> Studio: when reading from a large read-only multipage tiff

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffWriter.java
Each tif file has its own MultipageTiffWriter.  Each MultipageTIffwriter has a buffer pool of up to 3 images.  When the file approaches 4GB in size, the MultipageTiffWriter is no longer used, and a new one is created to continue writing to a new file.  However, its bufferPool was never released.  This caused major problems with a dataset with extremely large images, but more generally, this was an unnecessary memory leak. This commit clears the pool when the finish() function is called (which happens when the file approaches 4GB and a new one is created).
> Studio: Fixes memory leak in Multipage Tiff writer.

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/ImageByteBuffer.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
Also uses allocateDirect rather than allocate.
2250 x 255
Testing AllocateDirect versus Allocate on a dataset of 192 images 2250 x 2250 x 2 bytes (i.e. 192 * 10.125MB = 192 MB) with the script: "
```
start = System.currentTimeMillis();
mm.data().loadData("C:\\Users\\Nico Stuurman\\IMages\\imageData", false);
end = System.currentTimeMillis();
mm.scripter().message("It took: " + (end - start) + " ms");
```
10 times for each gave:
Old code: 6.2 +- 0.3 seconds
Allocate: 6.2 +- 0.9 seconds
AllocateDirect: 6.0 +- 0.83 seconds
Interestingly when run under the debugger in IntelliJ, Allocate was much slower than Allocate Direct (9.1 +- 2.0 seconds).
Not a huge difference, but the more images are in the dataset, the higher the performance improvement should be.  Also, this should create less work …
> Studio: MultipageTiff reader: re-use ByteBuffer instead of allocating a new one for each image. 

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/ImageByteBuffer.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
Realized that all that was missing was a rewind of the ByteBUffer. Redoing, since this should greatly reduce memory footprint, as the FileChannels are hodling on the to the ByteBuffers they are reading in (at least in the JVM we are currently using).
> Studio: Redo Reuse of ByteBuffer in MultiPageTIffReader.

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/ImageByteBuffer.java
This should fix bugs with 8-bit and RGB images.  Converting that code to work with Direct Buffers seems to negate any speed advantages with shorts.  Sorry for the mess.   Hopefully, the memory fixes will still work.
> Studio: Revert ByteBuffer from Direct to normal.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
Needed in some unexpected situations.  Use the Options mechanism, but do not expose in Options dialog.
> Studio: Make it optional to unlock autofocus during Z stack.

- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDataManager.java
- mmstudio/src/main/java/org/micromanager/data/internal/StorageRAM.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/ImageByteBuffer.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
While opening a Multipage Tiff dataset consisting of a few hundred 4GB files, the computer ran out of its 256GB of memory.  Researching this issue showed that this memory was associated with the FileChannel and/or File not closing.  I do not know if this is bug in the version of the JVM we are using, or a general problem, but it makes it impossible to go through large datasets that were opened in virtual mode.  This PR (branch is poorly named) changes the way MultipageTIffReader works, by closing the FileChannel and FileHandle whenever the Reader switches to another File.  I was afraid that closing and opening File Handles would be costly, but do not see significant slowdown on my systems.
This PR also switches back from using Direct Buffers to non-direct.  Direct Buffers do not open …
> Multi-page Tiff Reader, avoid direct memory to fill up.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/testacquisition/TestAcqAdapter.java
Hopefully avoids unwanted/unexpected behavior.
> Studio: TestAcqJ: abort when user closes the display window of the Test Acquisition.

- buildscripts/nightly/nightlybuild_macOS_deps.sh
Because Boost 1.77.0 does not appear to work with the latest Apple clang++.
GNU Libtool libraries need to match the command-line libtool, so use the version that matches the current one from Homebrew. (Jenkins build machine will receive a matching upgrade.)
> Upgrade the boost and GNU libtool for Mac build

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/MultipageTiffReader.java
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorExecutor.java
- plugins/Duplicator/src/main/java/org/micromanager/duplicator/DuplicatorPluginFrame.java
We encountered Micro-Manager data where some of the image metadata json was not terminated with `"}`.  It would be ideal to figure out how that happened and ensure this will never happen again, but to be able to still read this data I added code to terminate the json string if not properly terminated.  This will have a tiny performance penalty, but save other data too.  Please advice whether or not this should be included. 
The other half of the PR give user feedback when the Duplicator plugin finds nothing to duplicate.  Sorry to bring these unrelated things together in one PR, can split out if that works better.
> Read bad mp tiff files, and better UI feedback in Duplicator plugin

- mmstudio/src/main/java/org/micromanager/events/internal/CoreEventCallback.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
Should fix issue #1948.
CoreEventCallBack was never told about the current acquisition engine.  My only worry is that the changed order of initialization in MMStudio may cause unforeseen problems.   Hope that Mark can review.
Closes #1948.
> Studio: Make CoreEventCallback aware of the current acquisition engine.

- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/FileSet.java
- mmstudio/src/main/java/org/micromanager/data/internal/multipagetiff/StorageMultipageTiff.java
- mmstudio/src/main/java/org/micromanager/internal/utils/ProgressBar.java
Tested under various scenarios, looks OK.
> MultipageTiff writer: warn against killing MM while filesets are being closed.

- mmstudio/src/main/java/org/micromanager/data/internal/PropertyKey.java
- mmstudio/src/main/java/org/micromanager/internal/propertymap/NonPropertyMapJSONFormats.java
I wonder about the representation.  It would be nicer to store them as a propertymap rather than a string, will need to look into that before merging. Since these data have not been stored yet (will need to check format of MDA Settings stored from MDA window), that may still be possible without backward compatibility issues.
> Studio: now actually saves MDA Settings in file.

- mmstudio/src/main/java/org/micromanager/internal/PropertyEditor.java
event so that it can save cleanly and no longer throws a null pointer exception on shutdown.
> Studio: PropertyEditor now subscribes to ShutdownCommencing

- .gitignore
These are created by the nightly build script.
> Add macOS disk images to .gitignore

- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
Not sure, but I hope this will fix the occassional display not showing images.
> Studio: avoid AWT killing null pointer exception in Display.

- mmstudio/src/main/java/org/micromanager/internal/utils/DefaultAutofocusManager.java
(previously only after opening the dialog).
Closes #2009
> Studio: AutofocusManager now lists persistent autofocus choice after starting up

- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/menus/ConfigMenu.java
Studio: avoid 2 x system cache updates during startup.
The core will update the system cache after loading the hardware config,
so there is no need for the Java code to do it again.  loadSystemConfiguration
used to update the cache at the end.  This has been removed.  Calling code
will need to update the cache itself if it so desires.
> Faster startup: Avoid 2 x system cache updates during startup.

- mmstudio/src/main/java/org/micromanager/internal/ConfigGroupPad.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultApplication.java
- mmstudio/src/main/java/org/micromanager/internal/MMStudio.java
- mmstudio/src/main/java/org/micromanager/internal/MMUIManager.java
- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
- mmstudio/src/main/java/org/micromanager/internal/menus/ConfigMenu.java
- mmstudio/src/main/java/org/micromanager/profile/internal/gui/HardwareConfigurationManager.java
So far, the Micro-Manager UI has always unloaded the existing configuration and reloaded it from file when saving a configuration.  Depending on the hardware, this can be a time-consuming action.  Thinking about speeding up some of the UI components, I realized there is no need for this except possibly to check quickly whether the new configuration file is faulty (please correct me if I am wrong in this assumption).  Over the many years using this, I have never found a problem.  
This PR keeps the existing configuration in memory after saving a new config file.  In limited testing with hardware, I have not found a problem, and it does speed things up quite a bit.
> No reload when saving the configuration file

- mmstudio/src/main/java/org/micromanager/internal/dialogs/IntroDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/introdialogparts/ConfigSelectionUIController.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/introdialogparts/FastInitializationUIController.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/introdialogparts/ProfileSelectionUIController.java
Will not show the checkbox if the core does not have this feature.  Code was modeled after other UIControllers in the IntroDialog.  Moved all 3 controllers into their own package to not clutter the internal.dialog package too much. 
Tested.  Can be merged even without the Core Feature present (although not very useful without it;).
> Studio: Adds fast initialization checkbox on Splashscreen.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
This not only simplifies the code, but also makes displaysetting behave more consistent.  
Closes #2029
> Remember ChannelDisplaySettings upon any change in settings.

- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/PLogicControlFrame.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/PLogicControlModel.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/PLogicControlPlugin.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/ASIPLogic.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/PLogicCell.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/model/devices/PLogicState.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/IOCell.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/LogicCell.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/DeviceTab.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/IOCellsTab.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/TabPanel.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/tabs/WizardTab.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/wizards/SquareWaveConfigPanel.java
- plugins/ASIPLogic/src/main/java/com/asiimaging/plogic/ui/wizards/SquareWaveDisplayPanel.java
-add progress bar when loading cells and when loading settings from json
-dialog boxes to prevent from easily switching between devices
-physical i/o panel will now update correctly when switching between devices
-add optional custom clock source to square wave generator wizard
-square wave display now scales with the dataset
-square wave signal generator had "Source Address" renamed to "Trigger Address"
-display currently selected device name above tabs
-add milliseconds display for wizard when using internal clock
> ASIPLogic: additional fixes and improvements

- mmstudio/src/main/java/org/micromanager/internal/PropertyEditor.java
- mmstudio/src/main/java/org/micromanager/internal/utils/ShowFlags.java
I still do not fully understand why this happens, but this prevents it from happening.
> Studio: prevent crash on shutdown when PropertyEditor is open.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/testacquisition/TestAcqAdapter.java
- mmstudio/src/main/java/org/micromanager/internal/MMUIManager.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
Adds:
- selector for the current Z drive, including indicator of current position (will only work with callbacks)
- GoTo button for top and bottom, only active in absolute mode
- Proposed Z-step value that can be applied with a single button click. The proposed value is currently 5 x the pixel size, but after adding this feature to the pixel size calibration it can be read from that source.
> MDA window Z slices section feature additions

- .github/workflows/apidoc.yml
Appears to no longer be in ubuntu-latest runners.
> CI: Ensure SVN is installed

- mmstudio/src/main/java/org/micromanager/internal/ConfigGroupPad.java
- mmstudio/src/main/java/org/micromanager/internal/MMUIManager.java
- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
- mmstudio/src/main/java/org/micromanager/internal/menus/ToolsMenu.java
This PR identified a few places where subsequent function calls would update the System Cache.  This led to slow down in the UI, especially when the hardware was slow to respond.  
On such such occurrence was changing a Configuration Preset in the UI, which used to cause two subsequent updates of the cache.  After this merge, such updates should feel a bit snappier.
> Avoid double caching

- buildscripts/Ant/windowsprops.xml
If the computer does not have VS2019 installed, use VS2022 for the build.
For now, it will still required that VS2022 is installed with the option "MSVC v142 - VS 2019 C++ x64/x86 build tools".
This will facilitate migrating the actual build to VS2022 tools.
> Allow Ant build scripts to use VS2022

- mmstudio/src/main/java/org/micromanager/Application.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/AffineEditorPanel.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/CalibrationListDlg.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/ConfigDialog.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelConfigEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelConfigExtraPanel.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelPresetEditor.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/PixelSizeProvider.java
- mmstudio/src/main/java/org/micromanager/internal/dialogs/introdialogparts/PixelConfigExtraPanel.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/ConfigPreset.java
- mmstudio/src/main/java/org/micromanager/internal/hcwizard/MicroscopeModel.java
- mmstudio/src/main/java/org/micromanager/internal/pixelcalibrator/PixelCalibratorDialog.java
Adds dxdz, dydz, and OptimalZUm to the pixel Size configuration dialog, and saves these settings in the config file.  Should only be merged after the corresponding PR for mmCoreAndDevices has been merged.
I hope the UI is still workable for people:
> Pixel config: UI for new core pixel Size config functions

- buildscripts/nightly/genreport_Windows.py
(This had been broken for a log time.)
> Fix path in nightly build C++ warning reporter

- buildscripts/fetchdeps.xml
Just maintenance.
The macOS automated builds (which use Ant from Homebrew) were already using the latest version because Homebrew Ant bundles Ivy. A default Ant installation (used in Windows automated builds) does not bundle Ivy.
> Upgrade Ivy version to latest

- plugins/pgFocus/src/main/java/edu/umassmed/pgfocus/PGFocusFrame.java
This fixes the error described in #2075 in the pgFocus plugin. The plugin uses a property name for the `Calibration Curve` property that differs from the one defined in the device adapter in the case of only a single letter.
https://github.com/micro-manager/mmCoreAndDevices/blob/a9b83246ca9154c4e20b125df72a40027de2d8c8/DeviceAdapters/pgFocus/pgFocus.h#L117
I am guessing that this previously worked because getting properties from the core by name used to be case insensitive; this likely changed sometime after 2018.
> Fix calibration property name in the pgFocus plugin

- bindist/any-Windows/StartMMStudio.m
Implemented a check for MATLAB Version to either place Guava.jar before MATLAB's system classpath for Matlab versions before 2022 or to treat it as the other jars for Matlab versions from 2022 on.
This was discussed in Issue #2080
> Update StartMMStudio.m for recent MATLAB versions

- mmstudio/src/main/java/org/micromanager/quickaccess/internal/DefaultQuickAccessManager.java
- mmstudio/src/main/java/org/micromanager/quickaccess/internal/QuickAccessFrame.java
Previously, they would not honor the settings because both the manager and the panel were called during shutdown, one closing the panels, the other saving whether or not the panels were open.
It is still a bit mysterious why often the option to always re-open the panel was not honored, but this code behaves much better.
Closes #2087
> Studio: QuickAccess Panels now re-open as desired.

- mmstudio/src/main/java/org/micromanager/internal/dialogs/AcqControlDlg.java
Should fix a problem with the new acquisition engine not returning to the middle of the stack (it would always go to zero) when using relative Z
> Studio: Set ZReference in acquisition settings.

- mmstudio/src/main/java/org/micromanager/internal/MainFrame.java
This allows MM to work on Windows under Java 11 and is probably a good thing in any case.
> Studio: MainFrame: Only do weird menu thing on Mac.

- bindist/x64/ImageJ.cfg
- buildscripts/installer_Windows.iss
These should not be needed with JDK >= 9, and we are now shipping 11.
> Remove DPI awareness settings for Windows

- buildscripts/nightly/nightlybuild_macOS_deps.sh
- buildscripts/nightly/nightlybuild_macOS_mm.sh
Make the build work with the latest Apple toolchain.
Closes #2102.
Before merging, I should test correct loading of:
> Update mscOS C++ dependency build

- buildscripts/fetchdeps.xml
`ant -f buildscripts/fetchdeps.xml show-deps`: print dependency graph
`ant -f buildscripts/fetchdeps.xml ivy-report`: generate HTML report, also including graphs
> Add Ant targets to display Ivy report/graphs

- buildscripts/ivy.xml
Remove the BioFormats reader/writers (which, as best as I can tell, are not used) and x86 32-bit native packages for JOGL.
One of the BioFormats dependencies (turbojpeg), in particular, was causing problems in #2116. But removing these also saves a lot in installer size.
> Remove unnecessary (and problematic) clearcl/ClearVolume dependencies

- buildscripts/installer_Windows.iss
The current JRE 11 installed over an existing version with JRE 8 fails to launch, so delete before installing.
Closes #2122.
> Windows installer: delete previous JRE

- mmstudio/src/main/java/org/micromanager/internal/ConfigGroupPad.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultApplication.java
Unchecking "sync channel exposure time between main and MDA window" will now really stop changing exposure times when selecting a new channel  (i.e., the exposure time stays as it is rather then be set to the value associated with the specific channel that was chosen).
> Studio: unscramble exposure-channel sync mess.

- mmstudio/src/main/java/org/micromanager/profile/internal/UserProfileAdmin.java
> Studio-Profile: when Profile writes are locked, show user rather than only log.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultShutterManager.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
This prevents downstream strangeness
> Studio: Wait for shutter to be not busy when either our code or the core opens or closes it. 

- buildscripts/nightly/nightlybuild_macOS_mm.sh
As opposed to from 3rdpartypublic, where there is the future danger of version mismatch.
> macOS: get JOGL natives from the packaged JAR

- buildscripts/nightly/nightlybuild_macOS_mm.sh
Unfortunately #2146 did not work: the resulting build fails to launch (apparently after invoking `java`).
Disable bundling the JRE for now.
I believe the reason is that I forgot to add the correct entitlements when code-signing (the JVM requires these to enable things like JIT), but I have not yet found a configuration that works. So let's revert for now.
> macOS: disable bundling of JRE

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/display/DisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/DisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplayManager.java
- mmstudio/src/main/java/org/micromanager/display/internal/DefaultDisplaySettings.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayUIController.java
- mmstudio/src/main/java/org/micromanager/internal/DefaultAlbum.java
- mmstudio/src/main/java/org/micromanager/internal/SnapLiveManager.java
This PR needs a minor version update of the Studio version since it adds a function (and 3 static variables) to DisplaySettings and it adds a function to DisplayManager.
DisplaySettings now can be provided with a key that will be used in WindowPositioning.  For this to take effect, a method for the calling code to provide initial displaySettings was needed.  Since all the calling code was already providing DisplaySettings right after constructing the display, it made sense to add that function in any case.
> Adds Window Position Key to DisplaySettings and uses it in MDA, Album and Preview

- buildscripts/nightly/genreport_MSBuild.py
Probably the log format changed with VS2022 -- it's gotten a bit buggy so work around. (The script had been failing for a while but we don't currently block the build on failure to generate the warning report.)
> Fix MSBuild log parser

- mmstudio/src/main/java/org/micromanager/acquisition/internal/acqengjcompat/AcqEngJAdapter.java
Ugly workaround was to add a dummy Z stack whenever channel definitions request z offsets.
Closes #2157.
> Studio AcqEngj: fix incorrect behavior in channel offsets.

- mmstudio/src/main/java/org/micromanager/acquisition/internal/MMAcquisition.java
- mmstudio/src/main/java/org/micromanager/data/internal/DefaultDatastore.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/DisplayController.java
- mmstudio/src/main/java/org/micromanager/display/internal/displaywindow/MDScrollBarPanel.java
- plugins/Deskew/src/main/java/org/micromanager/deskew/DeskewAcqManager.java
This was mainly due to Datastore SummaryMetadata not being set synchronously.
> Fix bug displaying wrong channel names in Inspector Window

- plugins/Deskew/src/main/java/org/micromanager/deskew/DeskewFrame.java
Apperently, the Coords were sorted in the wrong order, so that processing would not start until the complete dataset was read in.  I can not fully wrap my head around the sort order, but the data seem to sort correctly now.
> Deskew plugin: fix problem with processing existing data.

- plugins/CRISP/src/main/java/com/asiimaging/crisp/CRISPFrame.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/CRISPPlugin.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/panels/StatusPanel.java
- plugins/CRISP/src/main/java/com/asiimaging/crisp/plot/PlotFrame.java
- plugins/CRISP/src/main/java/com/asiimaging/devices/crisp/CRISP.java
- plugins/CRISP/src/main/java/com/asiimaging/devices/crisp/CRISPFocus.java
- plugins/CRISP/src/main/java/com/asiimaging/devices/crisp/CRISPTimer.java
Refactor CRISPTimer to use a SwingWorker instead of a SwingTimer, this allows the CRISP query commands to run a worker thread rather than making the queries on the EDT (Event Dispatch Thread).
The ASIStage device adapter recently had a change to the CRISP device description which broke device detection in the CRISP plugin.
Device detection relies the device description, so a small change makes that work again.
> ASI CRISP: fix MS-2000 device detection, improve plugin responsiveness with multithreading
